libnoname/noname

mode/single.js
1.先手起手应该少摸一张牌。
2.阵亡后新登场的武将摸牌数位4，不是maxHP。
=> 新1v1模式调整，根据官方规则

game/game.js
Change the "game.exit" function to restart the app for WKWebview users using ios. And added the "macintosh" field to the judgment of "lib.device"
=> Change game.exit, added the macintosh field to the judgment of lib.device

game/game.js, mode/connect.js
=> Revert "fix: adjust the edit box style to fix the text overflow problem 🐛"

game/game.js
Add the default accept value of '*/*' to the HTML selection file label
=> Add the default accept value of '*/*' to the HTML selection file label

game/game.js
=> Lieren2023 patch 7

card/standard.js, mode/boss.js
1.修复无懈的一处事件名错误（from 鬼神易）。
2.修改讨逆技能代码中的变量名，优化代码结构，修复了非挑战模式报错的问题。
3.修正boss.js的代码缩进。
=> 1.修复无懈的一处事件名错误。2.修改讨逆技能代码中的变量名，优化代码结构，修复了非挑战模式报错的问题。3.修正boss.js的代码缩进。

game/game.js
=> 选项-显示新增显示扩展武将图片，设为默认开启

mode/guozhan.js
get is double and gzZhang Lu's update
=> 国战双势力机制变更，国战张鲁技能更新

character/huicui.js, character/sp.js, character/xianding.js
1. 修正桓范结算的一个问题；
2. 修复孙寒华标记显示的一个问题。
=> 修正桓范结算和孙寒华一个bug

character/clan.js, character/mobile.js, character/sp2.js, mode/guozhan.js
1.族钟会【迂志】添加摸牌数标记，并修复一个ai问题
2.珠联璧合写法优化，修复重叠数组无法读取珠联璧合的bug
=> 珠联璧合写法优化+族钟会标记显示摸牌数

character/mobile.js
1.三个十常侍技能调整
2.蒋干陈年技能效果更新+身份国战模式可用
=> 蒋干陈年技能效果更新+十常侍调整

game/game.js, layout/default/layout.css
现在背景图片或（鏖战）音乐均可以指定扩展文件（`ext:`）。
添加`game.addBackgroundMusic`和`game.removeBackgroundMusic`，用于自定义（鏖战）背景音乐选项。
确保`lib.filter.targetEnabled`相关的函数的返回值为布尔类型。
支持兼容版。
=> Add the ability to customize the background image or music.

game/game.js, game/package.js
=> Code: Optimization: The Game: Part 1.

card/mtg.js, card/yingbian.js, card/yongjian.js, character/collab.js, character/ddd.js, character/diy.js, character/hearth.js, character/offline.js, character/shenhua.js, character/sp.js, character/xianding.js, game/game.js
用间篇相关代码重构——新增`lib.element.player.gift`和其他相关函数等。
新增`lib.filter.ignoredHandcard`及相关函数，用于检测不计入手牌上限的牌。
将`lib.init.addJsForExtension`改为`lib.init.jsForExtension`，且现在支持按顺序加载文件。
各种修复。
支持兼容版。
=> The Use of Spies, and various fix.

card/yingbian.js, character/diy.js, character/extra.js, character/sb.js, character/tw.js, character/xianding.js, game/game.js, layout/default/layout.css, layout/mobile/layout.css
修复部分应变代码。
添加`compareShowCardBefore`。
修复谋孙权〖统业〗的AI。
`game.linexy`支持更多颜色字符串，及修复因错误的颜色字符串导致线条没有颜色的问题。
=> Miscellaneous fix.

game/game.js, layout/default/layout.css, mode/boss.js, mode/brawl.js, mode/chess.js, mode/doudizhu.js, mode/guozhan.js, mode/identity.js, mode/single.js, mode/stone.js, mode/versus.js
继续修复CSS。
根据一直以来的部分反馈，去除`lib.element.player.changeHp`和`game.chooseCharacter`的触发限制。
=> Miscellaneous fix: Part 2.

game/game.js
在扩展启动代码中，输入以下代码测试，即可在lib.init.onload执行前执行所需的异步函数
```js
if (!Array.isArray(lib.onload)) {
lib.onload = [];
}
lib.onload.push(function* () {
const data = yield fetch(`https://www.baidu.com?date=${(new Date()).getTime()}`).then(r => r.text());
alert(data);
});
```
=> lib.onload支持传入GeneratorFunction以解决需要异步函数的问题。修复制作扩展的函数被懒加载的问题以及回滚deleteDB函数

game/config.js, game/game.js
修复`lib.init.jsForExtension`，并支持添加回调函数。
实验性替换为一个新的可用更新地址。
=> Fix lib.init.jsForExtension, and update URLs.

game/game.js
修复和`lib.element.event.untrigger`有关的代码（#260），和`get.skillRank`的未定义参数的错误。
=> Fix lib.element.event.untrigger related code, and get.skillRank.

game/game.js
=> trySkillAudio更改

mode/guozhan.js
将国战建国改为真正的修改身份和势力，取消单向换皮+友方存储操作
=> 国战建国机制写法修改

mode/identity.js
将身份模式的教程改成`genCoroutine`形式，避免三角形缩进，同时减少代码量。
=> [Suggest] modify identity totorial genCoroutine

card/yongjian.js, character/clan.js, character/huicui.js, character/sp.js, game/game.js
添加`get.cardNameLength`，用于获取一张牌的字数，并废弃`lib.skill.dcweidang.getLength`。
=> Add get.cardNameLength.

character/clan.js, character/jsrg.js, game/game.js
=> Various fix.

game/game.js
=> [BugFix] fix genCoroutine.

card/mtg.js, card/yongjian.js, character/gwent.js, game/game.js
=> Keep compatible.

character/mobile.js, game/game.js
为damage函数添加一个unreal参数，并简化手杀曹嵩的写法
=> 为damage函数添加一个'unreal'参数来表示视为受到伤害

character/mobile.js, game/game.js
为damage函数新增'unreal'参数，表示视为受到伤害，修改手杀曹嵩
=> 为damage函数新增'unreal'参数，表示视为受到伤害

game/game.js
增加`get.is.vituralCard`，用于判断一张牌是不是虚拟牌。
同时也添加了`get.is.convertedCard`判断转换牌，`get.isordinaryCard`判断普通牌。
=> [Suggest] get.is.vituralCard

character/mobile.js, character/refresh.js, character/sb.js, character/shenhua.js, character/sp.js, character/tw.js, character/yijiang.js, game/game.js, mode/identity.js
删减hasZhuSkill的权限，取消主公技的特定模式限制
添加isZhu2()判别，主公技在init和reinit时不满足条件下不获得此技能
调整明忠模式和部分武将的主公技机制逻辑
=> 主公技机制修改简化+遗留问题修复

README.md, game/game.js
选项1 显示技能名拼音：在武将资料卡显示技能名拼音
选项2 显示武将名拼音等信息：在武将资料卡显示武将名及其拼音、性别、势力、体力等信息
=> 资料卡显示技能名拼音、武将名拼音等信息

game/game.js
将`game.import`相关的东西基本改成`genCoroutine`。
=> [Experimentalize] Asyncify `game.import`.

game/game.js
将扩展的`${skill}_append`通过`addSkill`加到本体，用于解决可能已经不存在的萌新经典问题。
（顺带问一下，要不要解决扩展中添加`lib.config.all.characters`后因没读取到文件而报错的小问题）
=> [Suggest] Extension Skill Support Append Info

game/game.js
- `gnc.async`改名为`gnc.of`
- 移除`gnc.await`，同时移除`lib.genAwait`
- 其余信息可参考commit的信息
- > 暂未处理`lib.genAsync`
=> [Alter] 修改`genCoroutine`的机制

game/game.js, mode/identity.js
- 修复`identity.js`中`lib.gnc.async`的遗留
- 修复`content.die`中残留的`let`
=> [BugFix] 一些玄学的遗留bug

game/game.js
- 现在可以将`Array<StepFunction>`传入`lib.init.parsex`，其中`StepFunction`为`(event: Event, args: Parametres<ContentFunction>, result: EventResult): Event`
- 现在可以将`GeneratorFunction(event: Event, args: Parametres<ContentFunction>)`传入`lib.init.parsex`
- > 传入一个`object`会得到`Now Yet Incomplete`报错
=> [Experimentalize] `parsex`支持更多参数

game/game.js
=> Revert "chooseToMove 拖拽+动画效果，手机版无法拖拽"

game/game.js
- 修复`game.import`异步化的大多问题
- 修复异步加载后`precontent`和`content`中this指针失效
- 修复`game.switchMode`加载模式时模式未加载完成
- 调整一些杂项函数
=> [Multi] 近期问题的尝试修复

layout/mode/boss.css
=> Fix and format the CSS.

character/jsrg.js
- 现在【帐灯】需要当前回合角色与技能拥有者同时反面才能发动技能
=> 处理Issue #325 | 修复承邹氏【帐灯】

character/jsrg.js
- 修复`jsrgjixiang`中step 0的变量`list`仍然在step 1中使用
=> #360 | 修复承甄宓【济乡】

character/sp.js, character/sp2.js, character/yijiang.js
添加OL后台武将张既，吕伯奢，费祎[均unseen]
bugfix
=> OL后台武将+bugfix

game/game.js
1、修复了副将不能识别audioname2的bug
2、现在audioname2里面可以直接放路径或数字了（对应音频文件名为skill+playername）
3、优化了charactercard中播放技能语音的问题
=> trySkillAudio第二次优化

game/game.js
=> The Database Update: Extra.

game/game.js
```js
player.when(['xxAfter', ...args])
player.when('xxAfter')
player.when( 'xxAfter', 'yyBegin')
player.when({player: 'xxAfter'}})
player.when({player: 'xxAfter'}, {global: 'yyBegin'})
```
=> player.when添加其他时机形式，且增加filter2和removeFilter2

game/game.js
=> inherit更改，支持嵌套

game/game.js
- 不再使用`Object.defineProperty`为`lib.creation`赋值，直接用`get method() {...}`的形式定义属性
---
=> [Enhancement] 更改`lib.creation`的原理

game/game.js
由于一些主要的客户端在数据库版本上硬编码，因此回退数据库版本更新，扩展要改为读取"image"。
支持兼容版。
=> Madokaaaaaaaaaa!!!!!!!

game/game.js
- 添加`lib.filter.none(...args: any[]): false`，恒返回`false`，用于需要恒假函数的时候
---
- 添加`lib.linq.dom`，用于使用LINQ的方法创建`dom`元素
> 目前只能创建`div`元素
- - Example:
```Javascript
const dom = lib.linq.dom;
dom.div(
"#Test.class.name.test", // id为Test, class为["class", "name", "test"]
dom.attr("test", "ok"), // attr是Attribute的缩写
dom.stl("color", "#FFFFFF"), // stl是Style的缩写，因为存在style元素，故这里用缩写
dom.stl("text-align", "center"),
"Hello World", // innerHTML为"Hello World"
dom.div( // 创造子元素
"Test2.class.name.test2",
dom.stl("text-align", "center")
)
)
```
---
=> [Enhancement] 添加一些函数

game/game.js
=> 为addJudgeNext添加牌的位置判断

game/game.js
让useCard的exculded,directHit,customArgs在执行事件时不会被覆盖;让chooseUseTarget支持自定义选择目标数,并优化原逻辑
=> 优化useCard,chooseUseTarget

character/sb.js
=> 更换谋貂蝉【离间】ai策略

game/config.js, game/game.js
修复明置相关代码。
现在`get.objectURL`会缓存已经生成过的URL。
将大部分`indexOf`替换为更容易阅读且性能略高的`startsWith`或`includes`。
兼容测试通过。
=> The Readability Update.

game/game.js
- 增加`Player#setStorage`, `Player#updateStorage`和`Player#updateStorageAsync`第三个参数，为`true`时将调用`Player#markSkill`
- 增加`Player#removeStorage`第三个参数，为`true`时自动调用`Player#unmarkSkill`
---
- 增加`Player#setMark`，用于将标记值调成至某一具体的值
=> [Enhancement] `Storage`系列函数直接调用`markSkill`

game/game.js, layout/default/menu.css
备注：兼容版无法预览音频文件，可能是因为不能播放blob数据的原因。
其他功能正常，包括游戏内播放，修改武将信息的保存数据
=> 修复代码编辑器ui bug，修改playAudio的onerror，扩展界面增加阵亡配音功能

game/game.js
使用game.callFuncUseStepCache可将某函数的返回值暂时存入_status.event中，step跳过后清除。使用该机制优化了chooseToDiscard函数。
=> 使用缓存机制，优化了存有大量手牌时，chooseToDiscard的AI的计算速度。增加一个公用的缓存方法

game/game.js
=> 资料页试听阵亡配音先改回旧版

game/core-js-bundle.js, game/game.js, layout/mode/stone.css
导入[core-js-bundle](https://github.com/zloirock/core-js)，从此编写代码时可以使用绝大多数最新最热的函数。
增加`lib.compatibleEdition`，用于判断当前环境是否为兼容版。
现在`game.updateBackground`和`game.playBackgroundMusic`支持解析`db:`前缀的项目。
兼容测试通过。
=> The Polyfill Update.

game/game.js
让`cardNameLength`可输入字符串牌名直接输出牌名字数
=> 让`cardNameLength`可输入字符串牌名直接输出牌名字数

game/game.js
将`get`的大部分函数改成了`lambda`函数并重构了部分函数以提升性能。
同时增加了`get::event(): Event`和`get::event<T>(key: string): T`，用于直接获取当前事件，而不需要使用`_status`变量。
> 带`arguments`的函数则转成了新的形式，去掉了`function`关键词。
=> 优化`get`中函数的性能并提供一个新的函数

card/yongjian.js
=> 更新yongjian.js

game/game.js
=> 修复`get`函数存在传入类数组无`map`方式

character/clan.js, character/mobile.js
1. clanlieshi
- add no action logging
2. yijin
- fix exception when no available target
=> QOL for yijin & lieshi

character/extra.js
=> 修复神贾诩的一个 bug

game/game.js, mode/connect.js
将`lib.element`中的主要属性全部`class`化，大幅规范代码，且一定程度上提高性能。
优化联机模式加入服务器的用户体验，且有效避免因部分情况导致的无限重启的死循环等。
**亟需进一步测试。**
=> The Object-oriented Update

game/game.js
运用mixin机制，为以后同时给`VCard`和`Card`添加方法做好基础。
给`VCard`新增6个方法，用来规范地判断等价性，且待后人补充完善。
（未完待续）
=> The Mixin Update.

character/sp.js, game/game.js
修改了`$throwEmotion`及其相关的一系列函数；
新增`rotate`参数，让投掷表情可以随机落点和空中旋转。
效果如下图所示
=> 修改了`$throwEmotion`及其相关的一系列函数

game/game.js
使用`class`重构了`game.dynamicStyle`，同时做出了一个违背祖宗的决定，增加了还算足够的文档，至少让每个方式都有对应的类型提示
> 虽然并没啥用，该看不懂还是看不懂，建议直接看类注释的`@example`
=> Game DynamicStyle Classified and Documentified Refactor

game/game.js
修改changeHujia函数，增加失去护甲的log，对应谋曹仁等武将的不因伤害而失去护甲的机制；
将护甲抵挡伤害的log移动至changeHujia函数
修复一个因damage函数引起的护甲失效时damagepop不正确的bug
=> 完善护甲机制，修复护甲失效时damagepop不正确的bug

game/game.js
=> 完善trySkillAudio注释/拆分

game/game.js, layout/default/layout.css
现在`game.roundNumber`会随着运行不断广播。
解耦`game.updateRoundNumber`，分离出`ui.updateRoundNumber`。
修复`ui.click.ok`。
更换部分对象成员的赋值语法，使得支持兼容版。
修复切换布局时所用的加载屏幕。
兼容测试通过。
=> The Multiplayer Update: Extra.

character/extra.js, game/game.js
=> 修复`ui.create.identityCard`在触屏模式的问题

game/game.js
现在`handler`在每个`step`的开始和末尾都会执行一遍。
在`option`这个参数中可以读取到`state`，用来表示现在是在这个`step`的`"begin"`还是`"end"`。
兼容测试通过。
=> More about handlers.

mode/guozhan.js
修复引入“群雄割据”后，国战模式不会因达到人数而变野的bug
修复全场只剩一个势力的时候无视变野的可能性直接算获胜的bug
=> 国战野心家数和亮将相关bug修复

.gitignore, game/game.js
传参没改，只改了内部实现
当然，最主要是以后addtempskill里写{global:"xxx"}也没问题了
=> tempSkills参数归一化

game/game.js
此pr为夜白@nigthmoon提供
增加长按卡牌的信息显示
=> 夜白：增加cardintro信息显示

.eslintrc.json, game/core-js-bundle.js, game/game.js, layout/default/layout.css, mode/connect.js
现在保证了`core-js`最先加载。
联机模式房间正式支持动态人数。经多次测试可认定不会出现错误。
删除一些和联机模式有关的CSS，因其会影响生成的动态CSS。
修复`get.modetrans`，避免出现“undefined 模式”。
=> The Multiplayer Update: Part 2.

game/game.js, game/src/lib/announce.js
我们在 #681 的基础上提供了一些跟扩展相关的函数：
- `game.hasExtension(name): boolean` - 检测给定扩展名的扩展是否启用
- `game.hasExtensionInstalled(name): boolean` - 检测给定扩展名的扩展是否安装
- `game.hasExtensionLoaded(name): boolean` - 检测给定扩展名的扩展是否加载完成
同时，我们在扩展加载完成时提供了两个Announce时机:
- `Noname.Init.Extension.onLoad <- string` - 当一个扩展加载完毕时触发，传递值为扩展的名字
- `Noname.Init.Extension.$NAME.onLoad <- void` - 当一个名为`$NAME$`的扩展加载完毕时触发，传递值为`void`
这两个Announce时机因认定为常用而将被封装，但目前因未想好这两个Announce时机的名字而未提供封装。
注意，因为目前加载扩展的原理，这两个Announce时机会在**所有扩展都加载完毕**时触发。
=> Add Some Extension Methods.

character/shenhua.js, character/standard.js, game/game.js
注: 在调试步骤中`定义的变量只在当前输入的语句有效`
在技能中调试技能content相关的信息
```js
await event.debugger();
```
在技能中调试触发此技能事件的相关的信息
```js
await trigger.debugger();
```
```js
var fragment=document.createDocumentFragment();
ui.create.div(fragment);
ui.create.button(list[i],type,fragment,noclick);
```
在async content中，如果你不需要等待一个事件的结果，那你可以不需要写await了
```js
async content(event, trigger, player){
event.target.equip(event.cards[0]);
player.draw();
}
```
=> 实现异步事件的debugger方法，一系列涉及position的函数支持传入DocumentFragment元素，优化async content写法

game/game.js, layout/default/layout.css
1、parseSkillAudio小重构，彻底炸掉playSkillAudio
2、修复nobracket样式错误，.skill改为弹性布局（看不出区别，如果不放心可以不合）
3、arrangeTrigger补丁，以及更加强大的getParent
=> 彻底炸掉playSkillAudio

card/standard.js, character/collab.js, character/jsrg.js, character/sp.js, noname/library/index.js
=> 部分武将技能ai优化

layout/default/layout.css, noname/get/index.js
=> nodeintro太抽象了，一时半会搞不好，先回滚

noname/ui/index.js, noname/util/struct/promise-error-handler/unknown.js
=> fix: rebase error.

noname/library/element/vcard.js
=> 修复关羽武圣牌视为无花色BUG

noname/get/index.js, noname/init/index.js, noname/library/element/vcard.js, noname/ui/index.js
=> fix current bugs.

card/yongjian.js, character/standard.js, noname/game/index.js, noname/library/element/gameEventPromise.js, noname/library/index.js
终于！
终于！
现在〖战象〗终于修好了！
以及顺便修复某些人随地扔的分号垃圾（
=> Finally fix the gift mechanic.

character/standard.js, noname/library/element/gameEventPromise.js
①
let chooseCardResult = await player.chooseCard().forResult();
选择的卡牌：chooseCardResult.cards
②
let cards = await player.chooseCard().forResult('cards');
选择的卡牌：cards
③
let [success,cards,targets] = await player.chooseCardTarget().forResult('bool','cards','targets');
success:是否做出选择。
cards:选择的牌。
targets:选择的目标。
=> gameEventPromise新增forResult方法，用于优化解构赋值写法

.gitignore, game/config.js, noname/init/index.js, noname/library/index.js, noname/library/update-urls.js, noname/ui/index.js
=> The URL update.

.gitignore, game/game.js, noname/init/import.js, service-worker.js
备注: 请各个客户端将node_modules/typescript/lib/typescript.js放到game文件夹内以正常启动ts解析功能
=> 添加解析ts的逻辑, exe使未找到的文件不返回html

game/game.js, noname/get/index.js
> 暂时没修复Safari不能打开的问题，毕竟**这事只能狂神来做**
=> 修复Safari的提示情况

character/gwent.js, noname/game/index.js, noname/library/element/button.js, noname/library/element/content.js, noname/library/element/gameEvent.js, noname/library/index.js
=> game.check初步拆分

noname/library/index.js
lib.sort排序函数只考虑了a_name，导致a_b_name排在错误位置，故需修改排序函数
=> fix：lib.sort排序函数修复

noname/library/assembly/index.js, noname/library/hooks/index.js
为了弥补check的api兼容，让assembly支持add匿名函数。
再次拷打狂神。
=> pref: allow anonymous function in asswmbly.

noname/library/assembly/index.js
=> fix: recursion.

noname/get/index.js
所有平台
完善无穷体力、体力上限、护甲显示
支持Infinity、'Infinity'、'∞'、'∞/∞/∞'等写法
通过
无需适配
=> fix：完善无穷体力、体力上限、护甲显示

mode/single.js
=> 无限火力模式专属牌堆

character/xianding.js
所有平台
logSkill时机无法触发
更改时机为useSkillAfter
通过
无需适配
=> fix：十周年糜夫人发动存嗣之后不能按闺秀说的回复体力

noname/ui/create/menu/pages/cardPackMenu.js
使用game.addCardPack添加卡牌包时，可以使用closeable:true选项，令玩家可以手动编辑牌堆（也即使用game.import导入卡牌包时，卡牌包信息页底下的那个“编辑牌堆”）
=> 使用game.addCardPack添加卡牌包时，可以使用closeable:true选项，令玩家可以手动编辑牌堆（也即使用game.import导入卡牌包时，卡牌包信息页底下的那个“编辑牌堆”）

noname/init/node.js
=> 修复创建文件夹的bug

mode/guozhan.js
=> 国战官盗2023（先仅补充技能

character/extra.js, character/huicui.js, character/offline.js, character/refresh.js, character/shenhua.js, character/sp.js, character/sp2.js, character/tw.js, character/xinghuoliaoyuan.js, character/yijiang.js, character/yingbian.js, noname/game/index.js
所有平台
修复删除扩展不删除对应目录文件的bug；
添加一些技能combo，修复个别技能combo引用错误
无需适配
=> 删除扩展bugfix，combo添加

noname/game/promises.js, noname/library/update.js, noname/ui/create/menu/pages/otherMenu.js
所有。
@nonameShijian 提供的更新素材的代码，以及为此和服务器交互的API，亟待完善。
现在请求的URL改为[api.unitedrhythmized.club/noname](https://api.unitedrhythmized.club/noname)了。
并且，API改为
```
interface DownloadAssets {
// 要执行的操作，目前只有一个 downloadAssets，用于下载资源。
action: "downloadAssets";
// 仓库拥有者，默认为 libccy。
owner?: string;
// 仓库名称，默认为 noname。
repo?: string;
// 版本，根据仓库拥有的标签选择，默认为latest，但强烈建议在客户端决定后手动填写。
version?: string;
// 文件列表。
fileList: string[];
}
```
同时添加了`getLatestVersionFromGitHub`和`getTreesFromGithub`，以进一步减少请求量。
由于面向客户端的代码无需关心服务器情况，所以仅基本测试足矣。
内部修改，无需扩展适配。
=> The API Update.

character/diy.js, character/extra.js, character/huicui.js, character/jsrg.js, character/mobile.js, character/offline.js, character/sb.js, character/shenhua.js, character/sp.js, character/tw.js, character/xianding.js, character/yijiang.js
所有平台
为部分负面技能添加neg, halfneg标签；
删除【冯河】的combo；
combo补充
无需适配
=> 增补/修复部分技能标签

noname/game/index.js, noname/game/promises.js, noname/init/node.js, noname/library/index.js, noname/library/update.js, noname/status/index.js, noname/ui/click/index.js, noname/ui/create/index.js, noname/ui/create/menu/pages/exetensionMenu.js, noname/ui/create/menu/pages/otherMenu.js
所有客户端
如下所示
1. 修复判断最新tags的漏洞，修复asyncFilter导致EMFILE: too many open files错误，修复game.promises.readFile的类型问题
2. 对自动检测更新进行限制，每次会话只请求一次更新数据（只有退出app此次对话才会结束）
3.  对输入错误的token进行检验，以及尽量减少输入token的弹窗
4. 修改电脑端game.createDir逻辑使已存在文件夹不报错。修改导入扩展逻辑，支持导入esm扩展(必须有info.json)和ts扩展(运行的话需要客户端支持)
5. 其他类型修复
控制台测试，以及导入esm扩展
无
=> 限制自动检测更新，支持导入esm扩展，修复其他bug

noname/init/index.js
※在扩展被禁用的情况下彻底不加载扩展，修复联机模式无法进入官方服务器的bug。
=> v1.10.11.1

character/diy.js, character/huicui.js, character/mobile.js, character/standard.js
所有平台
combo, neg, halfneg标签补充；
修复【清严】
无需适配
=> bugfix，标签补充

noname/ui/create/menu/pages/exetensionMenu.js
=> fix import info.json

character/extra.js, character/mobile.js, character/shenhua.js, character/sp.js, character/xianding.js, noname/library/element/player.js
所有平台
[修复filterCard传参错误](https://github.com/libccy/noname/commit/cd6e6faeadac5f584d1e18c9e3267437c75b9647)；
[修复【连讨】ai](https://github.com/libccy/noname/commit/611714353b16eddcedad81c8a7cd2badd939851a)；
[调整【佐佑】为垃圾版本](https://github.com/libccy/noname/commit/58b9332a87b7947f0f87f9ce2f09a4032d67611b)；
标签补充
无需适配
=> filterCard传参修复，部分武将技能bug修复

game/game.js
#1247
使用`window.location.pathname`替换默认的`/`
=> 修复issue #1247: 使用反向代理有子路径时，serviceWorker的scope错误

noname/ui/create/index.js
所有平台
无
缺少lib.character[i][4]判断
无
无需适配
=> ui.create.characterDialog函数修复

game/package.js, index.html, noname.js, noname/game/promises.js, noname/init/import.js, noname/library/init/index.js, tsconfig.json
所有平台
~~“测了，能跑。” ——Spmario233~~
新武将模块的一些滞后操作
顺带发现了几个bug
- 增加了`game.promises.getFileList(dir: string): Promise<[folders: string[], files: string[]>`
- 在`noname.js`增加了`rootURL`
- 对`importCharacterPack`做了些修改
- 修复了`index.html`对自带API的引用修复
- 稍微格式化了下代码
- 让`lib.init.parsex`主动识别了`prettier`生成的代码
~~**测了，能跑。**~~
但应该确实能跑
无需适配，当然扩展也能把`__dirname`和`lib.assetURL`都替换一下，虽然现阶段没必要
=> 一个想不到好标题的PR

game/entry.js, noname/init/index.js
安卓端
重做由理版app
增加由理版升级逻辑判断
ok
扩展需要注意file协议切换到https协议后的影响
=> 增加由理版升级逻辑判断

character/clan.js, character/jsrg.js, noname/get/index.js
①起许劭【盈门】【评鉴】适配新武将定义类方法
②起许劭【评鉴】兼容cost写法
③将jsrg.js格式化为R的新prettier规则
④族钟会【挟术】修改
=> 起许劭适配新版character类，族钟会4改，格式化

noname/ui/click/index.js
所有平台
修复了[#1236](https://github.com/libccy/noname/issues/1236)提到的bug
更改了noname/ui/click/index.js的部分代码
通过
无需适配
=> bugfix，修复ui.click.target的targetprompt显示错误的问题

noname/library/index.js
①修复切换控制权的全局技能autoswap不能在chooseToGive交换控制权的bug
②格式化noname\library\index.js为新Prettier准则
=> autoswap添加chooseToGiveBegin时机，格式化

character/collab.js, mode/chess.js
=> 清除本体中lib.character[i]的数组检测

character/tw.js, character/yxs.js
所有平台
无
[twgongji修复](https://github.com/libccy/noname/pull/1295/commits/3de5122def39f70bd2e64623a542e6c0f67a3b4b)（修复方法参考[修复【弓骑】](https://github.com/libccy/noname/commit/e7d94af9b4254675ca25ed7025f0b188b3a63b41)）
fix：吕雉丢一张黑色牌就可以发动鸩杀
通过
无需适配
=> bug fix：twgongji修复、吕雉丢一张黑色牌就可以发动鸩杀

noname/library/element/character.js
=> 为Character类的get 4 增加proxy

character/yxs.js, mode/boss.js, mode/guozhan.js, mode/versus.js
所有平台
无
添加locked: false,标签
通过
无需适配
=> fix：技能无法被封印修复

character/refresh.js, noname/game/index.js, noname/get/index.js, noname/library/element/player.js
所有平台
联机模式测试时遇到的
get.character(name)为空则返回{}；
修复get.character相关的调用
联机测试无报错
无需适配，不过建议用get.character(name)替代lib.character[name]
=> get.character相关修复

character/refresh.js
所有平台
在非官方服务器联机的时候使用界左慈发动化身就会一直报错，严重影响游戏体验，故对此问题进行了修复。
#1302 
对界左慈的化身技能的代码进行了一部分更改。
将技能中在game.broadcastAll调用了 lib.character[event.card][0],改为了在该函数外部调用get.character(event.card, 0)获取性别，然后传入game.broadcastAll该函数的参数中,避免了在客户端执行 lib.character[event.card][0] 或 get.character(event.card, 0) 时发生 Cannot read properties of undefined (reading '0') 错误。
在非官方服务器和单人对战中进行了多轮测试，未见报错，同时角色性别随化身技能变化正常。
无
=> 修复 issue #1302: 非官方服务器下界左慈化身技能会导致报错问题的修复

character/diy/skill.js, character/extra/skill.js, character/huicui/skill.js, character/mobile/skill.js, character/sp/skill.js, character/tw/skill.js, character/yijiang/skill.js
所有平台
修复(#1320 )(#1321 )中存在的问题
【拼命】排除投降事件；
修复【息兵】【忍戒】【权计】ai
联机测试，客机荆轲可以正常投降
无需适配
=> bugfix，ai优化

character/clan/skill.js, character/onlyOL/skill.js, character/onlyOL/translate.js
=> 技能调整；minor fix

mode/versus.js, noname/ui/create/index.js
所有平台
添加get.distance；
删除已经废弃的precharacter
打开该模式看一眼
无需适配
=> 对决四国模式座位号修复

character/shenhua/skill.js
all
诗笺的任务喵（step转async）
把多个武将的技能转了异步，然后修复了之前cost传links的一个bug喵
所有武将都测试了一遍喵
没有发现问题哦
none
=> step转async：孙亮、许攸、卢植、蒯良蒯越、曹仁、庞德、袁绍、魏延、黄忠、姜维、刘禅、张郃、邓艾、孙策、张昭张纮、蔡文姬；bugfix

character/yingbian/skill.js
所有喵
被拷打了喵
箭头函数返回对象没有用括号喵
已经修复了喵
测试完成喵，没有问题喵（无论是否ai操作下喵）
没有喵
=> 修复bug喵_(:з」∠)_

noname/library/element/player.js
所有平台
`chooseSkill`函数没有返回值，以致其在使用异步写法时报错。
在`chooseSkill`函数末尾添加`return next;`
编写一个含有`const { result: { bool, skill } } = await player.chooseSkill(player)`，在修改前抛出一个错误。
在`chooseSkill`函数末尾添加`return next;`后，没有出现报错且`result`正常输出。
不需要
=> 修复chooseSkill没有返回值的问题

noname/util/sandbox.js, noname/util/security.js
所有
修复沙盒问题
1. 修复控制台的语法问题，可以再次使用var、for等结构
2. 提高了一些扩展使用替换本体函数兼容性
3. 防止了通过注入错误对象可能进行逃逸的行为
感谢一位不愿透露名称的神秘人帮助测试！
总共迭代了八个测试包找出了问题所在
暂无
=> 再次关闭全模式沙盒；修复控制台的语法问题；修复一个通过错误逃逸的漏洞；修复没有传递this到闭包函数的问题

character/sp2/skill.js
所有平台
bug fix #1284未修复到位
`if (targets[1].countCards("h") == 0) event.goto(targets.length > 2 ? 4 : 5);`
跳转有问题
[rehuoshui再次修复](https://github.com/libccy/noname/commit/fd9b1e309341fa8be2cbb66861fee81800196fe7)
通过
无需适配
=> rehuoshui再次修复

character/rank.js, character/xianding/character.js, character/xianding/characterReplace.js, character/xianding/skill.js, character/xianding/sort.js, character/xianding/translate.js, character/yijiang/characterReplace.js
=> 新杀谋张绣、新杀谋曹昂、新杀谋关平

character/shiji/skill.js
=> 为手杀蒋琬尽瘁加changeSeat标签

mode/guozhan.js
所有
国战荀攸奇策没有语音效果，没有劲
In guozhan.js, convert `audio: "qice_backup",` to `audio: "qice",`
手动测试
无
=> 修复国战荀攸奇策语音失效问题

mode/doudizhu.js, mode/identity.js, noname/get/index.js, noname/library/element/player.js, noname/ui/click/index.js
所有
1. 是诗笺喵的任务(？)，应该是哦，修复一下这个自动化测试的东西喵
2. 修复一下今天群里的误判喵
1. 对于test_game做了简单修复，不过因为暂停好像有bug所以禁用了它的暂停功能
2. 对于清洗函数体在多种函数体的支持喵
都进行了测试，可以正常工作
test_game大致没有异常喵，可以正常跑身份与国战（但可能缺乏更加丰富的武将技能测试）
清洗函数体已经用原问题的代码测试并通过
暂无
=> 修复test_game；修复函数体清洗对于异步函数体的支持

character/yijiang/skill.js
all
https://github.com/libccy/noname/issues/1452
修复满宠御策需要血量不为满才可发动的问题。
移除了一些冗余代码。
test in manchong
=> fix: fix yuce and remove redundant code

character/extra/skill.js, character/jsrg/skill.js, character/key/skill.js, character/mobile/skill.js, character/refresh/skill.js, character/sp/skill.js, character/sp2/skill.js, character/standard/skill.js, character/yijiang/skill.js, node_modules/@types/noname-typings/nonameModules/noname/library/element/player.d.ts
所有平台
【挥戟】跳过死人结算；
【扬戈】添加【密诏】描述；
【观势】添加ai；
【奋励】检查【平寇】是否生效；
mayHaveSha、mayHaveShan ts提示优化；
combo调整
无需适配
=> bugfix, add tags

character/shenhua/skill.js, mode/versus.js, noname/init/index.js
所有
修复bug哦
如题所述喵，修复了三个小bug哦
全部测试通过喵
无
=> 修复bug：国战英魂报错；security初始化没有await调用；联机2v2使用了未定义变量func

node_modules/@types/noname-typings/NonameAndroidBridge.d.ts, node_modules/@types/noname-typings/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/game/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/get/audio.d.ts, node_modules/@types/noname-typings/nonameModules/noname/get/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/library/element/client.d.ts, node_modules/@types/noname-typings/nonameModules/noname/library/element/player.d.ts, node_modules/@types/noname-typings/nonameModules/noname/library/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/status/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/error.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/index.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/initRealms.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/sandbox.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/security.d.ts, node_modules/@types/noname-typings/windowEx.d.ts, noname/init/index.js
无
跟进typings, 增加NonameAndroidBridge的类型提示
跟进typings, 增加NonameAndroidBridge的类型提示
无
无
=> 跟进typings, 增加NonameAndroidBridge的类型提示

character/shenhua/skill.js, noname/get/index.js, noname/init/index.js, noname/library/index.js, noname/library/init/index.js, noname/util/error.js, noname/util/initRealms.js, noname/util/sandbox.js
所有
1.诗笺喵提出的冗余代码喵
2.之前的联机时的动态代码在报错时无法跟踪喵
3.于吉的蛊惑的变量错误使用喵
1.移除了isArray替代的冗余代码喵
2.完善了报错信息的追踪喵
3.修复了于吉蛊惑的变量问题喵
1.基本测试已经通过，isArray恢复正常喵
2.基本测试已经通过，现在在客机执行主机的代码也可以看到详细的错误代码片段喵
3.把于吉的蛊惑跑了几遍喵，没什么问题了喵
暂无
=> 移除冗余的isArray替代；完善和修正报错信息；修复于吉的bug

character/collab/skill.js, character/key/skill.js, character/refresh/skill.js
所有平台
【离骚】人机会选自己凑数，受距离限制目标作为更低潜在目标；
神户小鸟的魔物衍生技能添加至derivation
无需适配
=> 【离骚】人机会选自己凑数；魔物衍生技能

character/collab/skill.js, character/mobile/character.js, character/old/character.js, character/refresh/character.js, character/yijiang/character.js, mode/guozhan.js
所有平台
- [minor fix：语音修复、台词修复等 #1469](https://github.com/libccy/noname/pull/1469)中于禁阵亡配音修复有问题
minor fix
- 修复诱因和背景中的问题
- [junk_sunquan阵亡配音修复](https://github.com/libccy/noname/pull/1489/commits/753ccefd6de34426374a8196b70a83bdf36b4c33)
- [derivation添加如意金箍棒](https://github.com/libccy/noname/pull/1489/commits/f0c60c906199a96c4cee666e1837179bb0f198f7)
通过
无需适配
=> minor fix：语音修复、台词修复等

character/sp/skill.js
=> 蒋琬【蓄发】印卡bugfix

character/extra/skill.js
全部平台
神华佗bugfix（@mengxinzxz的任务）
无
=> 神华佗滤心bugfix

character/old/voices.js
所有平台
无
minor fix：台词补充
- [旧马岱台词补充](https://github.com/libccy/noname/pull/1502/commits/49f6a0f99b3e1667a66f604b1880910c64a3483a)
- [旧王异台词补充](https://github.com/libccy/noname/pull/1502/commits/2953c6242105317043eb65a7920adf51ff9db096)
- [旧马谡台词补充](https://github.com/libccy/noname/pull/1502/commits/c34791f9665adaccf7e678253e100cb8d798c68e)
通过
无需适配
=> minor fix：台词补充

character/xianding/skill.js
=> 关樾奋恚bugfix

character/clan/skill.js, noname/get/index.js
所有
群里@Fox-⑧反馈的bug哦
**追加**
岁喵的反馈哦
重新调整了牌名的过滤，让锦囊牌不会被印杀的情况下被放过
另外印属性杀是应该不允许的，所以没有额外增加
**追加**
修正了正则表达式对于类似 name => ... 函数的匹配
印杀和印锦囊都工作正常
**追加**
新的正则表达式工作正常，主机成功把正确的代码发送到了客机
无
=> bugfix: 修复族王沦求心任意选项都可以印锦囊牌的bug；修复非异步单参无括号箭头函数的匹配失败问题

noname/get/index.js, noname/library/element/player.js
所有平台
很多函数没写JSDoc，所以来补补。
补充一些函数的JSDoc，不过没改noname-typings的d.ts文件，后续需跟进。
另外就是改动了player.removeGaintag，现在可以传Card了。
应该没问题
无
=> 补充函数的JSDoc

character/extra/skill.js, character/refresh/skill.js
=> 手杀神司马懿技能衍生改界

character/sp/voices.js
所有平台
无
minor fix：语音修复、台词修复
- 雅丹台词修复
通过
无需适配
=> minor fix：语音修复、台词修复

deno.json, noname-server.js, noname/get/compatible.js, noname/get/index.js
chrome端
为拥有`navigator.userAgentData`的浏览器进行适配（目前仅chrome和opera浏览器支持~edge就是chrome~，故只判断了chrome的情况）
顺带，`Get#event`的设计有问题，故计划下个版本废弃（或许）
增加`navigator.userAgentData`相关判断逻辑
测了，能跑
无需适配
=> 为`Get#CoreInfo`增加新内核特性

noname/get/audio.js
=> 修一个audio的八个

noname/game/check.js
=> 修复game.check的某处缓存问题

character/extra/skill.js
所有平台
手杀神司马懿【忍戒】写法修改
手杀神司马懿【忍戒】写法修改，抵消→响应
测了能跑
无
=> 手杀神司马懿【忍戒】抵消→响应写法修改

mode/brawl.js
所有平台
同姓之争没有排除没有姓氏的武将
加了段排除的代码
测过了，同姓之争没有出现没有姓氏的武将。
不需要
=> 同姓之争剔除没有姓氏的武将

character/sp2/skill.js
所有平台
@mengxinzxz 的《活动武将》cost化的时候图省事把本体的【天则】inherit过去了
不妨直接把本体的也cost化
【天则】cost化
点将单挑
无需适配
=> 【天则】async化

character/clan/skill.js, character/offline/skill.js
全部平台
王明山添加宝宝标记、周姬优化、族钟毓log修复
已测试
无
=> 王明山宝宝标记、周姬优化

character/offline/card.js, character/offline/character.js, character/offline/skill.js, character/offline/sort.js, character/offline/translate.js, character/yijiang/skill.js
all
新武将神曹仁，神刘表
线下卡牌【荆襄盛世】（ai待补充）
修复【通博】
=>  荆襄风云新武将，神曹仁神刘表

character/huicui/skill.js, character/shenhua/characterReplace.js, character/standard/skill.js, character/tw/characterReplace.js, character/yijiang/characterReplace.js, character/yingbian/characterReplace.js
=> bug修复，ai优化

noname/library/element/player.js
所有平台
萌新代码群有人使用类似`player.choosePlayerCard(target, "visible", {type:"basic"});`的代码选择其他玩家的牌，发现过滤器不按预期工作。
将原来传`button`进`get.filter`改成了传`button.link`。
测过了
不需要
=> [Bugfix]修复PlayerCard类函数使用get.filter函数错误的问题

game/directory.js, game/generateChanged.js
无
添加生成测试包的脚本
添加生成测试包的脚本
根目录下执行
```cmd
node game/generateChanged.js dbe7ce46e771304d2c1c9dac96bde522f3e8a3d0 
```
其中dbe7ce46e771304d2c1c9dac96bde522f3e8a3d0是某个commit的SHA
无
=> 添加生成测试包的脚本

game/generateChanged.js
无
路径分隔符在qq显示的bug
修改路径分隔符以修复qq显示的bug
生成，测
无
=> 修改路径分隔符以修复qq显示的bug

extension/boss/extension.js, node_modules/@types/noname-typings/Skill.d.ts, noname/library/element/player.js, noname/ui/create/index.js
所有
修复诸神降临的剑阁武将不显示图片的bug，添加Player.addSubPlayer的类型信息，typings增加持恒技的类型
能跑
无
=> 修复诸神降临的剑阁武将不显示图片的bug，添加Player.addSubPlayer的类型信息，typings增加持恒技的类型

mode/boss.js, mode/brawl.js, mode/chess.js, mode/connect.js, mode/doudizhu.js, mode/guozhan.js, mode/identity.js, mode/realtime.js, mode/single.js, mode/stone.js, mode/tafang.js, mode/versus.js, noname/game/index.js, noname/library/element/content.js, noname/library/index.js
所有
对未来规划进行的必要改动
模式的加载方式改为esm，不过还是兼容以前的写法
一个个测，来回测，没发现什么问题，就是源代码是一坨
无需适配，但最好跟进
=> 模式的加载方式改为esm

noname/game/index.js, noname/library/element/content.js
=> loadModeAsync更改

index.html, noname/game/index.js, noname/game/promises.js, noname/init/cordova.js, noname/init/index.js, noname/init/node.js
所有平台
`noname-server`提供`checkFile`和`checkDir`，但本体并没有用到
为三端提供`Game#checkFile`和`Game#checkDir`:
```
/**
* 检查指定的路径是否是一个文件
*
* @param {string} fileName - 需要查询的路径
* @param {(result: -1 | 0 | 1) => void} [callback] - 回调函数；接受的参数意义如下:
*  - `-1`: 路径不存在或无法访问
*  - `0`: 路径的内容不是文件
*  - `1`: 路径的内容是文件
* @param {(err: Error) => void} [onerror] - 接收错误的回调函数
* @return {void} - 由于三端的异步需求和历史原因，文件管理必须为回调异步函数
*/
checkFile(fileName, callback, onerror) { ... }
/**
* 检查指定的路径是否是一个目录
*
* @param {string} dir - 需要查询的路径
* @param {(result: -1 | 0 | 1) => void} [callback] - 回调函数；接受的参数意义如下:
*  - `-1`: 路径不存在或无法访问
*  - `0`: 路径的内容不是目录
*  - `1`: 路径的内容是目录
* @param {(err: Error) => void} [onerror] - 接收错误的回调函数
* @return {void} - 由于三端的异步需求和历史原因，文件管理必须为回调异步函数
*/
checkDir(dir, callback, onerror) { ... }
``` …
=> 添加文件检测和目录检测函数

character/offline/skill.js
所有平台
Uncaught (in promise) ReferenceError Cannot access 'player' before initialization
- 司马炎封土ai报错修复
通过
无需适配
=> 司马炎封土ai报错修复

noname/library/index.js
所有平台
安卓手机无法设置显示状态栏
- fix：显示状态栏无法保存设置
通过
无需适配
=> fix：显示状态栏无法保存设置

character/offline/skill.js
=> 主公钟会自重bugfix

character/huicui/skill.js, character/jsrg/skill.js, character/key/skill.js, character/offline/skill.js, character/refresh/skill.js, character/sb/skill.js, character/sp/skill.js, character/standard/skill.js, character/xianding/skill.js, game/codemirror.js, mode/identity.js, noname/library/element/content.js
all
chooseToMove支持拖动卡牌
电脑和手机都测了
十周年UI抄代码吧
=> chooseToMove支持拖动卡牌

card/extra.js, character/huicui/skill.js, character/mobile/skill.js, character/offline/skill.js, character/refresh/skill.js, character/sp/skill.js, character/standard/characterReplace.js, character/xianding/skill.js, character/yijiang/characterReplace.js, mode/guozhan.js
所有平台
群友反馈，@nonameShijian 反馈
详见commits标题
无
无需适配
=> bug修复，ai修复

.gitignore, noname/init/loading.js
全部平台
上次拆`proceed2`最后修完bug后忘pr了
修复了最后的`bug`
都是上次小白鼠群包的代码，他们说没问题，那应该没问题
同 #1708
=> TMD天煞的`proceed2`还在追我

noname/library/element/content.js
无
filterMove和TouchEvent有bug
[解决filterMove的问题](https://github.com/libccy/noname/commit/d2c33535d640fd6cb2621f47abdcaafcbc3f74ae)
[修复没有TouchEvent的问题](https://github.com/libccy/noname/commit/91e49e42e926c25ca9b7e809717a2591a828c908)
晋司马懿测试
无
=> 修复chooseToMove的bug

character/mobile/character.js, character/mobile/skill.js, character/offline/card.js, character/offline/character.js, character/onlyOL/skill.js
=> 谋孙坚bugfix；手杀贾充语音补充

character/mobile/skill.js, noname/get/audio.js, noname/get/audio.ts
所有
游戏过程中发现
修复换肤后播放错误阵亡配音的bug（这次牢狂要相信我）
sbanguo logAudio修正
测试通过
无
=> 修复换肤后播放错误阵亡配音的bug

game/codemirror.js
所有平台
编辑斗地主将池报错
使用原方法document.elementFromPoint
再次编辑无报错
无需适配
=> fix codemirror

noname/init/loading.js, noname/ui/create/index.js
无
有些问题
修复部分模式报错
**BREAK CHANGING:** 现在扩展的武将包的id将从`mode_character_xxx`改为`xxx`，卡牌包同上
基本上所有模式都尝试跑了几遍，目前没大问题
总之如果小白鼠暂时没别的问题的话，那就这样吧 
扩展的武将包的id将从`mode_character_xxx`改为`xxx`，卡牌包同上
如果原先有扩展包的分包，需要将`mode_character_xxx`改为`xxx`
=> 对读取相关的Bug修复

noname/util/initRealms.js
无
联机情况下一直都有点问题
尝试修正了下联机的问题
测了，能跑
无需适配
=> 修正目前联机的不少东西

noname/init/loading.js, noname/library/index.js
无
对破坏性更新的兼容
对`lib.characterPack`和`lib.characterSort`进行代理，在执行`get`, `set`和`defineProperty`操作时，将`mode_extension_xxx`自动转换为`xxx`
注意只对上述三类操作进行代理，其余操作需要自行适配
测了，能跑
除非同时存在`mode_extension_xxx`和`xxx`两个包，否则无需适配
实际上如果两个包的内容基本相同，无需处理
=> 对`mode_extension_`的兼容

character/sp/skill.js
=> 修复并优化【决生】ai

character/refresh/perfectPairs.js, character/shenhua/perfectPairs.js
无
群友反馈：国战孙策太史慈无珠联璧合
minor fix：珠联璧合补充re_taishici
通过
无需适配
=> minor fix：珠联璧合补充re_taishici

character/newjiang/skill.js, character/sp2/skill.js
=> 武将技能bugfix

character/onlyOL/skill.js, mode/guozhan.js, noname/library/element/content.js, noname/library/element/player.js
所有平台
转化装备遗留小问题
群友反馈技能bug
转化装备显示花色点数修改
修复转化装备无法正常移动的bug
部分技能bugfix
测了，过了
无
=> 转化装备显示/移动fix；技能minor fix

noname/ui/create/index.js
无
自由选将的搜索功能并不检索`xxx_ab`，导致搜索时关羽并不会显示神秘将军（也是关羽）。
令自由选将的搜索功能检索`xxx_ab`。
测过了
不需要
=> 修改自由选将的搜索逻辑

character/sb/skill.js, character/tw/skill.js, character/yijiang/skill.js
=> bugfix，子技能audio补充

character/diy/character.js
全部平台
骰子马钧xinfu_jingxie1未跟进手杀马钧的技能名改动
见标题
已测试
无
=> 骰子马钧精械bugfix

layout/others/dialog.css, noname/game/index.js, noname/init/index.js, noname/library/element/dialog.js
=> 完善动画函数和addNewRow()

noname/game/index.js, noname/library/element/content.js, noname/library/element/dialog.js
=> 优化移动动画，考虑缩放；优化牌过多时的折叠算法。

card/xianxia.js, character/diy/skill.js, character/huicui/skill.js, character/jsrg/skill.js, character/key/skill.js, character/offline/skill.js, character/refresh/skill.js, character/sb/skill.js, character/shenhua/skill.js, character/shiji/skill.js, character/sp/skill.js, character/sp2/skill.js, character/tw/skill.js, character/xianding/skill.js
=> bugfix，combo标签补充

noname/get/index.js, noname/library/element/content.js
无
①当扣减一名角色`Infinity`点体力上限时，若其体力上限为`Infinity`，扣减后其体力上限会意外的变为`NaN`。
②动态装备skills则是我自己diy武将有用，所以才加了个。
见commit标题
测过了
不需要
=> bugfix，添加动态装备skills

noname/game/index.js, noname/library/element/content.js, noname/library/element/dialog.js
=>  1.修复chooseToMove动画未完成前可以点击确定的问题 2更改一些拖动过程中临时元素的显示效果。 修改addNewRow中的一些小问题

.gitignore, layout/others/dialog.css, noname/game/index.js, noname/library/element/dialog.js, noname/library/index.js, noname/ui/create/index.js
1.修复addNewRow的bug。2.增加记牌器功能。3更改之前的css写法，兼顾低内核
=> 1.修复addNewRow的bug。2.增加记牌器功能。3更改之前的css写法，兼顾低内核

noname/game/index.js, noname/library/index.js, noname/ui/create/index.js
无
由于`game.classify`是`Object.groupBy`的特化版本，而无名杀引入的`core.js`已经保证无名杀可使用`Object.groupBy`，故经过讨论后，决定去除`game.classify`
将所有的`game.classify`改成了`Object.groupBy`，并进行了去特化处理
去除一处多余的`game.saveConfig`.
顺带格式化了一下代码
记牌器正常工作，且无明显BUG
无需适配
=> 去除`game.classify`

character/extra/skill.js, character/tw/sort.js
=> 分包修正，修复xin_simayi播放rezhiheng配音错误

layout/others/dialog.css, noname/init/polyfill.js, noname/library/element/player.js
增加任务的提示功能，方便玩家更快更清晰的获得自己的或者其他的玩家的技能动态，以及其他的有用的信息。
增加player.setTip()
增肌player.removeTip()
增加Number.prototype.toCardNumStr()
=> 增加设置人物的提示功能，新增player.setTip和player.removeTip方法

character/clan/skill.js, character/diy/skill.js, character/extra/skill.js, character/mobile/skill.js, character/refresh/skill.js, character/shenhua/skill.js, character/sp/skill.js, character/xianding/skill.js, character/yijiang/skill.js, layout/others/dialog.css, noname/library/element/player.js
无
`lib.element.player.addTip`添加全局以适配联机
修改`lib.element.player.addTip`的临时tip显示
`lib.element.player.removeTip`添加全局以适配联机
修改部分技能使用`lib.element.player.addTip`显示标记
测了，能跑
无
=> lib.element.player.addTip实际运用

layout/others/dialog.css
当牌很多时，过于拥挤，增加放大功能，方便查看。
修改css
控制台测试
=> 增加addNewRow卡的悬浮的悬浮放大功能

character/mobile/skill.js, character/offline/sort.js, character/sp/skill.js
=> 手杀界钟会权计bugfix

character/clan/dynamicTranslate.js, character/jsrg/skill.js, character/refresh/skill.js, character/sb/skill.js, character/sp/skill.js, character/sp2/skill.js, character/xianding/skill.js, mode/guozhan.js, noname/library/element/player.js
=> 技能调整，bugfix

character/refresh/skill.js
无
测试时遇到
回滚了新杀界沮授的【渐营】提示标记
双将荀攸测试标记
无
=> revert 新杀界沮授【渐营】提示标记

card/extra.js, card/gujian.js, card/huanlekapai.js, card/swd.js, card/yunchou.js, card/zhulu.js, character/key/skill.js, character/mobile/skill.js, character/shenhua/skill.js, character/sp/skill.js, noname/library/element/player.js
全部平台
联机发现无锋剑未添加equipskill属性
1.补充一些装备遗漏的equipskill属性；
2.修改凤千早怀柔ai；
3.directgain及directgains改为broadcastAll
测了
无
=> 补充一些装备遗漏的equipSkill属性

character/huicui/skill.js, character/refresh/skill.js, character/xianding/skill.js, character/yijiang/skill.js, mode/single.js
=> bugfix，ai补充调整

card/mtg.js, character/hearth.js, character/sp/skill.js
=> 修复部分技能重铸recastingLose参数传入null的bug

node_modules/@types/noname-typings/NonameAssemblyType.d.ts, node_modules/@types/noname-typings/nonameModules/noname/library/element/dialog.d.ts, node_modules/@types/noname-typings/type.d.ts
=> 更正与完善AddNewRow的相关的一系列类型提示

character/diy/card.js, character/diy/skill.js, character/key/skill.js, character/mobile/skill.js, character/offline/skill.js, character/refresh/skill.js, character/shiji/skill.js, character/sp/skill.js, character/xianding/skill.js, character/yijiang/skill.js, character/yxs.js
无
张顺飞全责
消灭技能判定中的非红即黑，改为`switch`判断
能跑
考虑到扩展有技能的判定也是非红即黑，推荐扩展主进行修改。
=> 消灭技能判定中的非红即黑

node_modules/@types/noname-typings/HTMLDivElementEx.d.ts, noname/init/polyfill.js
=> 将div.css改成HTMLElement.css

character/sp/skill.js, mode/boss.js
=> 都市王、潘淑bugfix

card/standard.js, character/clan/skill.js, character/jsrg/skill.js, character/mobile/skill.js, character/onlyOL/skill.js, character/sb/skill.js, character/yijiang/skill.js, layout/newlayout/global.css, layout/others/dialog.css, noname/game/index.js, noname/get/index.js, noname/library/element/content.js
青釭剑类技能在额外结算时过早失去效果
见commits标题
测了
=> 结算调整，bugfix

noname/library/element/player.js
=> 修改tip的重叠显示问题

node_modules/@types/noname-typings/Skill.d.ts, node_modules/@types/noname-typings/type.d.ts, noname/game/index.js
=> 更新Mod类型提示。详细见commit

character/tw/skill.js
全部
@mengxinzxz ，孟新志的任务
见commits
已测试
无
=> 瞒天过海bugfix

node_modules/@types/noname-typings/Skill.d.ts
=> 改正刚发现的一些Mod中的错误。

character/mobile/skill.js, character/sb/skill.js, noname/library/assembly/buildin.js, noname/library/element/player.js
=> 修复tip的bug;技能调整。（详见commit）

node_modules/@types/noname-typings/Skill.d.ts
=> 完善类型提示(详见commit)

character/rank.js, character/refresh/skill.js, character/sp/characterReplace.js, character/standard/character.js, character/standard/skill.js, character/standard/sort.js, character/standard/translate.js, mode/boss.js
全部
@mengxinzxz 孟新志的任务
见commits
已测试
无
=> 补充遗漏的标准版乐进；大宝适配国战

character/extra/skill.js
=> 技能调整（见commit）

character/mobile/skill.js, character/sp/skill.js, character/yijiang/skill.js, layout/others/dialog.css, noname/library/index.js
=> 部分武将[裴秀，沮授，沙摩柯],封印技能,增加tip标记显示。

character/mobile/skill.js
=> 修复曹髦的ai卡死的bug

node_modules/@types/noname-typings/type.d.ts, noname/library/element/player.js
=> 完善有关玩家的actionHistory相关的类型

character/mobile/skill.js
N/A
- popup改动： 之前该技能获得mark并获得技能会触发两次logSkill
- filter改动：之前该技能会在所有`mbqianlong_addAfter`时机不正确地触发
- 修改`lib.skill.mbqianlong.popup`
- 修改`lib.skill.mbqianlong.filter`
打一把
=> 修复曹髦mbqianlong的filter & logSkill

character/mobile/skill.js, character/offline/card.js, character/offline/skill.js, character/offline/translate.js
=> 装备牌"白虎骁骑"；【清正】框大小增加

noname/library/element/content.js, noname/library/element/player.js
选择一或多个数值
prompt: String
prompt2: String
list: Array[Numbers[] | Object{min: Number, max: Number, base: Number, prompt: String}]
terminal: Number
forced: Boolean
filterSelect: Function(num, index, event)
filterOk: Function(event)
optprompt: String | Function(num, index)
processAI: Function(event)
=> chooseNumbers

node_modules/@types/noname-typings/nonameModules/noname/library/element/dialog.d.ts, node_modules/@types/noname-typings/nonameModules/noname/util/pagination.d.ts, noname/library/element/dialog.js, noname/ui/create/index.js, noname/util/pagination.js
全部
搜索和筛选各玩各的
创建ui.create.pagination,，修改自由选将搜索逻辑， 修改类型信息
测了
十周年
=> 创建ui.create.pagination,，修改自由选将搜索逻辑， 修改类型信息

character/offline/skill.js, character/sp/skill.js
全部
@mengxinzxz ppp
见commits
已测试
无
=> 马玩、幽司马懿bugfix

noname/ui/create/index.js
版本更新在即，搜索面临夭折风险。故临时出山修复。
如果与下面的筛选条件耦合，逻辑复杂，不易更改。为方便起见，所以计划与下面的筛选“各跑各的”进行搜索。
后人若想更改，再另行完善吧
测试了，除了不能搭配下面搜索条件搜索，未发现问题
=> 修复自由选将搜索的bug。

noname/library/element/player.js
所有
在进行挑战模式时发现更换boss后装备栏占位错位
如题
通过
改了removeEquipTrigger要看一下
=> 修复removeEquipTrigger没有移除vcardsMap里的card的bug

noname/library/element/card.js
无
给牌添加/移除应变条件实现较为麻烦
封装了俩函数用于给牌添加/移除`cardtag`
单机测过了，能跑。
联机也测过，但样本不是很足。
不需要
=> 添加addCardtag和removeCardtag

character/refresh/skill.js
全部
一个chooseNumbers的应用例子
见commits
已测试
无
=> 修改奇谋为chooseNumbers写法

character/jsrg/character.js, character/onlyOL/voices.js, character/refresh/voices.js, mode/brawl.js
=> 配音修正，bugfix

noname/library/index.js
无
现在联机没有了服务器的限制导致经常被炸房，故增加禁止不同版本和扩展玩家进房功能（仅房主设置有效）。
=> 联机模式增加禁止不同版本和扩展玩家进房功能

card/extra.js
=> 白银狮子bugfix

noname/library/index.js, noname/ui/create/index.js
增加联机模式记牌器开关(房主设置对所有人生效)；修复联机禁止不同版本进房功能无效的问题
=> 增加联机模式记牌器开关

character/onlyOL/skill.js, character/sp/sort.js
无
冲突回滚分包补充
冲突回滚的OL董翓分包补充
OL谋关羽【威临】封牌时机调整
测了能跑
无
=> 冲突回滚分包补充；minor fix

game/dedent.js, service-worker.js
所有
使用serviceWorker会导致import-with语法会报错
1.修复使用serviceWorker会导致import-with语法会报错的问题
2.添加[dedent.js](https://github.com/dmnd/dedent)(MIT)
3.添加部分Vite的特殊的查询参数
示例:
raw: 返回资源的原始内容字符串
```js
import string from './noname.js?raw';
// 打印该文件的字符串形式
console.log(string);
```
worker和sharedworker: 返回一个 Web Worker 或 Shared Worker 构造函数
```js
// 普通worker
import myWorker from 'url?worker';
new myWorker();
// 普通sharedworker
import myWorker2 from 'url?sharedworker';
new myWorker2();
// 模块worker
import myWorker3 from 'url?worker&module';
new myWorker3();
// 模块sharedworker
mport myWorker4 from 'url?sharedworker&module';
new myWorker4();
```
url: 返回资源的 URL 而不是文件内容
```js
import logoUrl from 'logo.png?url';
img.src = logoUrl;
```
控制台测试
无
=> 添加dedent.js(MIT)，修复导致import-with错误的问题，添加部分Vite的特殊的查询参数

character/shenhua/skill.js, character/sp/skill.js
无
群友、吧友反馈；
修复因cost事件无法定位到_status.event.target导致完全失效的【奋激】ai
详见commits标题
无
无
=> 技能bugfix、ai优化

character/diy/skill.js, character/extra/skill.js, character/shenhua/skill.js, noname/get/is.js
无
【翩舞】是六年前的代码，该翻新力。
【翩舞】改为异步写法，给`get.is.banWords`加上可选链。
测过了，能跑。
不需要
=> 【翩舞】改为异步；巴格非特斯

noname/init/loading.js
修改loadcard，多一层检测lib.config.mode
=> 防止某模式出现不属于此模式的卡牌

character/key/character.js, character/key/pinyin.js, character/key/translate.js
全部
《Heaven Burns Red》在与《Angel Beats!》的新联动中，公布了由依的全名：芳冈由依
将Key武将包中的“由依”重命名为“芳冈由依”
无需测试
无需适配
=> rename 由依 to 芳冈由依

character/sp/skill.js
=> OL郭照【椒遇】标记显示适配非红黑的其他颜色

character/sp2/skill.js, character/tw/skill.js
无
#2185解决character/tw/skill.js 冲突致使一个错误方法名未能及时修改；
顺便拷打@zhichaoxi2006 
- 打开你的Visual Studio Code，下载一个名为**Prettier - Code formatter**的插件![image](https://github.com/user-attachments/assets/6dd992ed-56f8-43b4-93c2-8f923f497eca)
- ![image](https://github.com/user-attachments/assets/c3161923-3cbf-4c1e-b575-477a9a38733c)
- 右键格式化文档，选用Prettier格式化
- 如果有"step XX";被圆括号包裹，可使用正则表达式全局替换还原
**正则表达式：**
查找内容：`\("step\s*(\d+)"\)`
替换内容：`"step $1"`
**.prettierrc内容：**
```json
{
arrowParens: "avoid",
bracketSpacing: true,
endOfLine: "lf",
printWidth: 999,
proseWrap: "preserve",
quoteProps: "as-needed",
semi: true,
tabWidth: 4,
trailingComma: "es5",
useTabs: true
}
```
继#2185 修正character/tw/skill.js里一个因冲突未能修改的方法名；
顺便优化个技能ai
未测试
无
=> 优化新杀辛毗【引裾】ai

character/mobile/skill.js
=> 修复势太史慈【振锋】技能必须两项全选的Bug

.editorconfig, .prettierrc
无
部分开发者无法使用`prettier.config.mjs`作为配置，故提供一份`.prettierrc`
增加`.prettierrc`
在`.editorconfig`中为`.eslintrc.json`和`.prettierrc`添加格式
测了，能跑.png
无需适配
=> chore: add `.prettierrc`.

noname/library/element/gameEvent.js
无
上次改`addTrigger`把他炸掉力（悲
修复`addTrigger`的问题，令其正常工作
修改前许劭使用【评鉴】发动【遗计】无事发生，
修改后许劭使用【评鉴】可以正常发动【遗计】，符合预期结果。
不需要
=> 修复上次修改的addTrigger问题

mode/guozhan.js
无
关联 #2155
去除国战选将的体力限制
国战无影响，正常运行
无需适配
=> 去除国战选将的体力限制

game/core-js-bundle.js
update core-js-bundle.js and typescript.js
=> update core-js-bundle.js and typescript.js

CONTRIBUTING.md, README.md, game/entry.js, game/game.js, noname/game/compatible.js, noname/init/index.js, noname/library/index.js, noname/library/update-urls.js, noname/library/update.js, noname/ui/create/menu/pages/otherMenu.js
无
在无名杀仓库组织化后，仓库原先的地址需要改变
将`README.md`及`CONTRIBUTING.md`中的`libccy/noname`改成了`libnoname/noname`
将代码中指向`libccy/noname`的链接都改成了`libnoname/noname`
顺带为之后的移除`Docker`相关文件进行准备
无需测试
无需适配
=> 将原先指向`libccy/noname`的链接改成`libnoname/noname`

mode/guozhan.js
无
那一年的更新，是吕范被通衢，调度过牌削弱成狗。
当时我看见吴国主公阵亡在乱军之中，这位老臣的叹息声至今萦绕耳畔。
那个瞬间我在想：若我能执掌策划之权，定要平衡所有势力！
如今PR权力就在眼前，我必须考虑这会不会是我此生仅有的机会。
我深知江东能有昔日“吴钩霜雪”的威名，吕范的过牌体系居功至伟。
重铸孙吴的霸业，吾等岂容推辞！
> 以上内容来源自AI
去除国战吕范【调度】一回合一次的限制
顺带将【调度】【典财】翻新了一下
测了，能跑
无需适配
=> 重振吕范荣光，我辈义不容辞！

noname/init/polyfill.js
无
贴吧有人问了下无名杀的洗牌的算法，看了一下，某种意义上过于信任现在的硬件配置了
由于著名的洗牌算法`Knuth Shuffle`带来的性能提升特别巨大，故换用了`Knuth Shuffle`算法
优化了`randomGet`和`randomSort`
去除了一些类型错误
测了，能跑
无需适配
=> 对一些数组的猴子补丁进行优化

.editorconfig, deno.json, noname-server.js
无
由于`Deno.js`自带权限管理，而无名杀在`deno.json`中提供的启动`noname-server`命令并未赋予写入权限，故在创建扩展/更改扩展时，会询问写入权限，导致无名杀本体软卡死
添加`--allow-write`
更新`deno.json`中的版本信息
测了，能跑，而且无名杀应该也没有别的`Deno.js`用户
无
=> 对`Deno.js`的一些更新

character/mobile/skill.js, character/refresh/skill.js, noname/library/element/content.js
狂神の动物世界
`lib.element.content.chooseButtonOL`功能拓充
`lib.element.content.chooseButtonOL`增加以下功能：
适配单机模式使用，返回同原`lib.element.content.chooseButtonOL`为角色`playerid`索引结果的`idMap`
可通过`targets`属性获取本次进行`lib.element.content.chooseButtonOL`的所有角色
**温馨提示：用角色**`playerid`**获取角色时记得区分单机和联机的**`idMap`**：单机为**`game.playerMap`**，联机为**`lib.playerOL`
修改使用`chooseButtonOL`的手杀蒋干【盗书】、界于吉【蛊惑】为仅使用`chooseButtonOL`
测了，能跑
代码示例-SP蒋干【盗书】（仅展示执行部分）
```js
mbdaoshu: {
*content(event, map) {
var player = map.player,
target = event.target;
var targets = [player],
names = lib.inpile.randomGets(3);
if (!names.length) return;
var map = {};
names.forEach(name => (map[get.translation(name)] = name));
if (get.mode() != "identity" && get.mode() != "guozhan") targets.addArray(player.getFriends());
targets.remove(target); …
```
=> lib.element.content.chooseButtonOL功能拓充

noname/library/element/GameEvent/compilers/ArrayCompiler.js, noname/library/element/GameEvent/compilers/ArrayCompiler.ts, noname/library/element/GameEvent/compilers/AsyncCompiler.js, noname/library/element/GameEvent/compilers/AsyncCompiler.ts, noname/library/element/GameEvent/compilers/StepCompiler.js, noname/library/element/GameEvent/compilers/StepCompiler.ts, noname/library/element/GameEvent/compilers/YieldCompiler.js, noname/library/element/GameEvent/compilers/YieldCompiler.ts, noname/library/element/player.js
无
在确定`async function () { await player.draw(); }`之类的代码能被正常运行时，通过排查发现，`AsyncCompiler`会排除参数个数为0的异步函数，而`StepCompiler`只关注函数的参数个数为0，故该函数会解析成`Step Content`，然后通过编译，这被认为是Bug而非Feature
顺带修复一些`player.when`的内容
对四类编译器的过滤函数进行限制，顺带`Step Content`不再只接收参数个数为0的函数
修正`player.when`的文档
为`player.when#finish`添加销毁检查
`测了，能跑`.png
一切用到`async function () { await player.draw(); }`的扩展都得改成正确的形式
=> 修复编译器引发的Bug，并添加一些细节

README.md, noname/library/index.js
无
README.md内的过时内容已不适配新版本；
常备主数量无经典选项
- 更新README.md里的过时内容
- 常备主候选武将数支持选3个
无
无
=> 细节优化[completed]

noname/library/element/player.js
None
When the player has two heroes, a bug in `player.setAvatar` caused the flashAvatar function to incorrectly set the second avatar.
See the diff
Done
None
=> fix: player.setAvatar

.devcontainer/devcontainer.json, .devcontainer/post-install.sh, .gitignore, .mise.toml
无
随着Dev Container的普及，无名杀的开发或许也该与时俱进一下
添加了Dev Container相关的文件，为无名杀开发进行基础配置
默认使用`pnpm`管理
测了，能正常运行Dev Container，但不保证一定能正常运行
无需适配
=> 添加Dev Container支持

noname/ui/create/menu/pages/exetensionMenu.js
=> 技能编辑器中显示和保存表层的getter和setter以及Symbol

mode/guozhan.js
无
1. 国战宗预发动承赏的目标看到的prompt是“give”，应该显示合适的提示语
2. AI挂装备时会对自己发动承赏从而无事发生，鉴于每回合限一次，这样显然劣于不发动
1. 添加了prompt
2. 修改AI判断目标是自己时不发动
人机测了没问题
N/A
=> 修复国战宗预的prompt和AI

mode/versus.js
=> fix: 修复了智囊 发动时描述问题。

card/zhulu.js, noname/library/element/player.js
全部
@1937475624 的任务
1.代传鬼神易的PR：修复了$gain2进行moveDelete动画时不更新卡牌信息的bug；
2.格式化逐鹿天下卡牌包；
详见commits
无
=> 代传鬼神易的PR；bugfix

noname/library/element/player.js
全部
@1937475624 的任务 修复客机有些标记看不见的bug
1.代传鬼神易的PR：移除了markSkill因nobroadcast不向客机广播的设定
已测试
无
=> 继续代传鬼神易的PR

character/huicui/skill.js, node_modules/@types/noname-typings/nonameModules/noname/library/element/player.d.ts, noname/library/element/player.js
无
* 吧友反馈淳于琼【粮营】在两人游戏时可以白嫖两张牌不分出去，或者三人游戏时可以摸三张牌只分一张
* ~~国战【存嗣】AI只考虑了国战仁德，但未考虑到目前的国战刘备使用的是界仁德~~ 将另开pr提交到`feature/guozhan-new`分支
* 文档中有错字
* 修复【粮营】逻辑
* ~~【存嗣】AI增加`rerende`判断~~
* 修改错字
能玩
N/A
=> Fix 粮营; fix typo

character/sp/skill.js, character/tw/skill.js
所有
群友反馈的问题
1.修复幻曹植翰鸿不能选择装备牌的问题
2.将OL董翓凤瑶黑桃牌离开装备区回血的结算调整至与官方相同，即角色死亡弃牌也会触发回血
已在本地测试
无
=> bugfix&技能修改

card/sp.js, card/xianxia.js, card/yingbian.js, card/yongjian.js, character/ddd/skill.js, character/onlyOL/skill.js, character/sp/skill.js
全部
联机玩pve发现
1.修复OL郭照【椒遇】，ddd甄宓【淼形】联机报错、OL界廖化【伏枥】报错、王匡手里有如董白给的黠慧杀选择弃牌而死循环的bug；
2.调整OL郭照【内训】的结算；
已测试
无
=> 技能修改；bugfix

mode/boss.js
无
#2386 
临时修复【映冢】无法获得技能的严重bug（无需加更新内容里）
两种情况都已测，能正常获得技能了
无
=> 修复【映冢】无法获得技能的严重bug

mode/boss.js
无
四季映姬的全名太长了，需要改为显示缩写。
见commits标题
测过了，能跑。
关于boss挑战黑名单接口：
```
//挑战祭风卧龙时禁用晋司马师
_status.banlist["boss_zhugeliang"] = ["jin_simashi"];
```
```
//也可以写成函数形式
//下为挑战boss刘备时禁选所有关羽
_status.banlist["boss_liubei"] = function (button) {
let { link } = button;
if (link.includes("guanyu")) {
return false;
}
return true;
}
```
注：上面的示例统统没有实装，此举仅为了开个接口。
不需要
=> bugfix；添加boss挑战黑名单接口

character/huicui/character.js, character/offline/index.js
=> E系列货号信息补充，武将调整

index.html
浏览器端
未来打算将`noname-server`移植到go语言以减小二进制大小，但go语言的部分机制与js端的不同，故提前兼容一下需要兼容的部分
对go语言相关的机制进行兼容，使现有的网页端代码能适配未来go语言的noname-server
测了，js端能跑，go端未来在go端适配 
无需适配
=> pref: add go compat code.

noname/get/index.js
无
resolve #2489
为`Get#info`提供了检测Symbol的情况
测了，能跑
无需适配
=> feat: provide symbol detection for `Get#info`.

noname/game/index.js
联机端
参考 #1854 ，现在为联机地址增加域名支持（和路径支持）
大幅度修改联机地址构建，在基本兼容以前地址的情况下增加对路径和域名的支持（但仍有创的部分）
顺带在某些情况下将减少判断次数，使性能得到微弱提升
因为在测试时突然发现，`localhost:8085`会被识别成`localhost:`协议下的`8085`，由于无名杀的联机协议为`WebSocket`，故直接判断
> 为啥会出现`localhost:8085`的地址，除了为了判断端口号情况，还有一个难蚌的原因：我的代理用到了8080端口，故只能换一个（
测了，似乎能跑
~~期待有更多的小白鼠前来测试~~
由于为了未来联机地址不被以往特性掣肘，故对于提供`ws://`或`wss://`前缀的地址（此时地址将被解析为合法URL），将不作端口号添加的特殊处理；鉴于提前添加协议的联机地址并不常见，故在此进行BREAK CHANGE
如果联机服务器的地址需要自行添加对应的协议，请自行添加8080端口，否则将按照ws/wss的默认端口80/443进行访问，导致错误
=> feat: add domain and path support for connect address.

layout/default/layout.css
所有
死亡的玩家在可选中状态下没有高亮喵（鬼喵的任务喵）
修复了因为灰度滤镜导致的盒阴影灰度化
使用了【武圣归来】测试通过喵。
暂无
=> 修复死亡玩家的可选中状态下的高亮效果

character/jsrg/skill.js, character/mobile/skill.js
无
鹿鹿的任务哦
为jsrg荡异和mb荡异添加了酒的效果
嗯，获得荡异后红温了很正常喵
我测试了一下没什么问题哦
而且本身也是复制酒的代码喵
无
=> 代鹿鹿提交荡异的酒效果

node_modules/@types/noname-typings/Skill.d.ts
=> 修改direct标签的描述

noname/library/element/content.js
全部
#2752 遗漏的判定牌的修复
1.修复addJudge检查销毁实体牌未考虑实体牌数大于1且其中有满足销毁条件直接终止结算的bug
更改了lib.element.content.addJudge的扩展需要跟进
=> 修复lib.element.content.addJudge检查销毁实体牌的bug

character/yingbian/skill.js, mode/guozhan/src/skill/character/yingbian.js
无
修复晋司马懿“雄志”和国战晋司马懿“骤霆”不能使用无目标牌的问题
修改了晋司马懿的技能“雄志”和国战晋司马懿的技能“骤霆”，增加了无目标牌的判断
已测试
修改过晋司马懿“雄志”或国战晋司马懿“骤霆”技能的扩展需要跟进
=> 修复雄志和骤霆不能使用无目标牌的问题

character/extra/skill.js
无
修复神孙策冯河效果与描述不符的问题（描述先免伤扣上限再给牌，原效果是先给牌再免伤扣上限）
修改了神孙策的技能冯河，调整效果顺序
已测试
修改过神孙策“冯河”技能的扩展需要跟进
=> 神孙策“冯河”效果调整

character/sp/skill.js, noname/library/element/content.js
南华老仙(@mengxinzxz )又追来了
修改【青书】的翻面摸三词条等级为3
修改【授术】给出的技能自己对OL南华老仙自身也可见
略微提升【青书】的效果词条筛选速度
略微提升【天书】的标记文本加载速度
被鬼神易拷打了，将扔牌特效放回lose事件前面
=> OL南华修改、回调useCard/respond修改

character/onlyOL/skill.js, noname/library/zhanfa.js
无
星语喵的任务喵
1. 去掉了莫名其妙的@/noname导入喵
2. 去掉了【绝崖】的chooseToRespond喵
1. 游戏可以打开了喵
2. 保持了和描述一致，很简单就懒得测试了喵_(:з」∠)_
无
=> 代星语喵提交PR喵；修复导入错误；修复【绝崖】可以响应打出的错误喵

noname/library/element/player.js
=> 修uninit的counttrigger的bug

character/extra/skill.js, character/old/skill.js, layout/default/layout.css
无
自己的任务
为神邓艾手牌标记添加三颜色滤镜做区分，并改异步写法
本体无扩展下进行过测试
无
=> 为神邓艾手牌标记添加三颜色滤镜做区分，并改异步写法

mode/doudizhu.js, noname/library/index.js, noname/library/zhanfa.js
添加农民死亡后另一名农民获得的遗产开关
修复部分战法的bug
=> 斗地主农民遗产版本开关
