libnoname/noname

game/game.js

修改lib.init.parsex函数，使其可以解析“step”嵌套“step”的函数。示例代码如下：
```
lib.skill._test = {
trigger: {
player: "phaseBegin"
},
content: function () {
game.log('step 0');
'step 0'
player.draw();
'step 1'
var next = game.createEvent('test');
next.player = player;
next.setContent(function () {
'step 0'
game.log('step 1-0');
'step 1'
game.log('step 1-1');
'step 2'
game.log('step 1-2');
player.draw(2);
});
game.log('step 2');
'step 2'
player.damage(2);
game.log('step 3');
'step 3'
var next = game.createEvent('test');
next.player = player;
next.setContent(function () {
'step 0'
game.log('step 3-0');
'step 1'
game.log('step 3-1');
player.draw(2);
});
}
};
game.addGlobalSkill('_test');
```

修改lib.init.parsex函数

---

game/game.js
mode/connect.js

noname verison: commit id [7327225](https://github.com/libccy/noname/commit/73272251af93b27c1816d5b90c23a9036f0e9b0c)
Chrome: 114.0.5735.133 (x86_64)
进入联机，输入较长的联机服务器地址如 `wss://127.0.0.1:8080/ws/servers/0001000001/aaaa/`，会触发文本溢出，在设置选项中也是如此，如下图所示
文本输入正常，文本样式正常，无溢出行为
限制输入框最大宽度，禁止内容换行，修复设置项中内容溢出问题
[commit bfb2063](https://github.com/PBK-B/game-noname/commit/bfb20634e8886d715ea45dc865070e611219a954#diff-254305d27f3c2d679dc0a57c9ef67925ec61ba2ea25101cfc0379faca44dd435)
隐藏溢出内容，修复内容溢出问题
[commit bfb2063](https://github.com/PBK-B/game-noname/commit/bfb20634e8886d715ea45dc865070e611219a954#diff-88f050735a0f13ebebac53db3767075ff91ae9c6d8341dd9f6441624c8061f83)
Source: [lzc-app 应用移植上游代码回馈计划](https://gitee.com/runui/lzc-game-noname)

fix: adjust the edit box style to fix the text overflow problem 🐛

---

game/game.js
mode/connect.js

noname verison: commit id [7327225](https://github.com/libccy/noname/commit/73272251af93b27c1816d5b90c23a9036f0e9b0c)
Chrome: 114.0.5735.133 (x86_64)
进入联机，输入较长的联机服务器地址如 `wss://127.0.0.1:8080/ws/servers/0001000001/aaaa/`，会触发文本溢出，在设置选项中也是如此，如下图所示
文本输入正常，文本样式正常，无溢出行为
限制输入框最大宽度，禁止内容换行，修复设置项中内容溢出问题
[commit bfb2063](https://github.com/PBK-B/game-noname/commit/bfb20634e8886d715ea45dc865070e611219a954#diff-254305d27f3c2d679dc0a57c9ef67925ec61ba2ea25101cfc0379faca44dd435)
隐藏溢出内容，修复内容溢出问题
[commit bfb2063](https://github.com/PBK-B/game-noname/commit/bfb20634e8886d715ea45dc865070e611219a954#diff-88f050735a0f13ebebac53db3767075ff91ae9c6d8341dd9f6441624c8061f83)
Source: [lzc-app 应用移植上游代码回馈计划](https://gitee.com/runui/lzc-game-noname)
> @Spmario233 没注意到我这边编辑器居然自动配置的是空格缩进，已经修复并且重新提交了。辛苦 review

[Resubmit] fix: adjust the edit box style to fix the text overflow problem 🐛

---

game/game.js

Fix the issue of "game.getDB" and "game. deleteDB" reporting errors without "lib.db".
Some browsers do not support "autoplay", so "onconplay" listening has been added.

Fix "game.getDB", "game. deleteDB" and "game.playAudio"

---

game/game.js
layout/default/layout.css

1.修复for in循环会出现game.js定义的新数组原型的问题。
2.增加Array.prototype.includes的polyfill。
3.修复layout.css的一个无意义大括号。
4.修复game.print不能打印部分函数的问题。
5.修复游戏自带控制台中的文字可能会不能选中的问题。

修复for in循环出现game.js定义的数组原型，增加includes的polyfill，修复layout.css的一个无意义大括号，修复game.print

---

character/sp2.js
mode/guozhan.js

修复许劭【评鉴】概率弹窗bug，添加许劭出牌阶段筛选技能限制
调整国战模式吕范、徐庶、公孙渊、彭羕、南华老仙的技能为2023年国战典藏版本
修复国战模式换副将选择“发现式”，一个技能每局只能变一次副将的bug（更改为每个技能对每名角色限变一次副将）
修复野心家建国后，击杀有队友的野心家执行摸牌奖励时仍然只摸一张牌的bug
修复野心家建国后，有队友的野心家击杀队友后不执行弃牌惩罚反而摸一张牌的bug

评鉴修复+优化，国战模式新技能+bug修复

---

card/standard.js
character/mobile.js
game/game.js

新增`lib.element.player.getHp`，用来获取在规则集上定义的一名角色的体力值（至少为0），并且因此同时修改了用来获取一名角色已损失的体力值`lib.element.player.getDamagedHp`。
同时，定义一个关于`lib.element.player.hp`的获取器有助于代码封装。
顺便根据官方的描述规范公告修改名称为〖冰冻〗，以及修复手杀曹休〖倾袭〗中的`chooseToDiscard`的提示错误。

Add lib.element.player.getHp and change lib.element.player.getDamagedHp.

---

game/game.js
layout/default/layout.css
mode/versus.js

使用`writing-mode`（兼容版使用`-webkit-writing-mode`）规范化竖排文本，从此以后的竖排文本不再需要使用`<br>`模拟，且完美支持拉丁字母书写体系（英文等），例如武将牌上的武将名。
以及修复小部分不规范的CSS。

Normalize vertical text using writing-mode.

---

game/game.js

由于`HTMLMediaElement.play()`在兼容版不会返回`Promise`，因此添加检查是否存在返回值。
为`lib.init.parsex`添加`"use strict";`，使其能在兼容版支持更多新特性。

Ensure the compatibility.

---

card/mtg.js
character/ddd.js
character/huicui.js
character/refresh.js
character/tw.js
game/game.js
layout/default/layout.css

现在`lib.init.parsex`可以无视函数中的注释了，可以避免一些因注释导致解析出错的问题。
修复了一些和重铸有关的问题。
经测试支持兼容版。

Add the ability for lib.init.parsex to remove all comments before parsing, and fix recasting related errors.

---

game/game.js

用于在扩展的precontent中调用，方便扩展在无名杀启动前加载需要的JS文件

新增lib.init.addJsForExtension方法

---

game/game.js

提供一个扩展可用的武将死亡配音标签。
在角色死亡时判断武将标签中存不存在以`die:`开头的标签，如果有则根据此标签的信息播放指定的配音。
格式如下: 
- `die:audio/die/sunce`
- `die:ext:test/foo/bar`
---
提供`game.getFileList`的第三个参数，使`game.getFileList`读取文件夹失败时调用。
同时兼容以前的特性。

Support character die-audio tag && Provide failure callback for game.getFileList.

---

game/game.js

现在`get.bordergroup`可以仅获取`border:`内容（若无则返回空`string`）。
现在`game.playAudio`无任何扩展名限制。
移除`Array.from`的polyfill。
修复和收藏模式相关的代码，且受害者更新后可自动恢复正常。

Fix! Fix! Fix! Fix!

---

game/game.js

声明了一个新名词`genCoroutine`，并添加了两个函数：`genAsync`和`genAwait`，作用如下：
- `genAsync(fn)`用于将一个`Generator Function`包装成`genCoroutine`，`genCoroutine`是个函数，接受参数与被包装的`Generator Function`相同，返回值为一个`Promise`。`genCoroutine`会不断遍历这个`Generator Function`生成的`Generator`，并将结果放入`Promise`中，等待该`Promise`结束后再继续遍历。换言之，`genAsync`相当于`babel`中于低版本模拟`async`的`_asyncToGenerator`
- `genAwait(gen)`是`genCoroutine`需要遍历`Generator`时调用的函数。换言之，`genAwait(gen)`就是将遍历出来的值放入`Promise`中，等待该`Promise`结束后再继续遍历。
---
目前`genCoroutine`的例子为`lib.init.onload`，代码如下：
```
onload:genAsync(function*(){
const libOnload=lib.onload;
delete lib.onload;
while(Array.isArray(libOnload)&&libOnload.length){
const fun=libOnload.shift();
const result=fun();
yield (fun instanceof GeneratorFunction)?genAwait(result):result;
}
...
}
```
这串代码展现了`genAsync`和`genAwait`的用法：
- …

[Experimental] genCoroutine

---

game/game.js

修复了原来扩展的`content`不为函数时会引发错误，从而被捕获并打印到控制台。

[Bug Fix] Fix abort when extension content is not function.

---

character/mobile.js

机制修改
调整结党除两组互不认可的常侍外，其余单向不认可关系均于第一次获取十常侍时进行随机配对
添加修正结束后若为单将模式则将武将暂时修改回十常侍
调整十常侍嘲讽语音播放逻辑
bug修复
修复结党能选最上面展示的常侍的bug
修复单将模式失去【党锢】后武将牌不变回十常侍的bug
修复段珪【叱吓】亮出的牌仍放回牌堆的bug

十常侍结党机制大改+bug修复

---

card/yongjian.js
game/game.js

使用`Object.defineProperty`和`Object.getOwnPropertyDescriptor`初始化导入包，避免导入内容失真。
支持兼容版。

Use Object.defineProperty, and Object.getOwnPropertyDescriptor to initialize instead.

---

game/game.js

将`genCoroutine`相关事件移至命名空间`gnc`中。该命名空间不会保存在任何可访问到的全局变量中。`lib.genAsync`和`lib.genAwait`作用不变。同时增加`lib.isGenCoroutine`、`lib.isGeneratorFunc`和`lib.isGenerator`三个函数，分别用于判定一个值是不是`genCoroutine`、`GeneratorFunction`和`Generator`。
---
提供`lib.onprepare`，用于在扩展全部加载后开始执行提供的操作（支持`genCoroutine`）；这些操作会在执行完扩展的`content`后等待执行完毕。
> EAP: 此功能或许有更好的替代方案

[Purify] genCoroutine && lib.onprepare

---

game/game.js

增加`get.cardNameLength`的第二个参数`player`，用于传入`get.name`中，获取经过`mod`转换后的真实牌。

[Suggest] advancify get.cardNameLength

---

game/game.js

修改`lib.gnc`的逻辑，现在`lib.gnc.await`可以给定任意参数，同时不再需要`gnc.next`作为辅助函数。
目前可以直接用`yield gnc.await(fun())`来直接异步未知`fun`情况的函数，而不需要判断是否是`genCoroutine`。同时`lib.gnc.await`可套娃调用，如`lib.gnc.await(lib.gnc.await(gen))`，这也是当`fun`为`genCoroutine`时`yield gnc.await(fun())`会发生的情况。

[Purify] Modify `lib.gnc`

---

game/game.js
mode/guozhan.js

添加`lib.characterGuozhanFilter`接口，使国战模式可读取除`mode_guozhan`以外的支持国战的武将包。
现在只要扩展的`pack.character.mode`属性为`guozhan`，就会被识别为国战武将包。
> 从某种意义上，应该自定义扩展中国战武将区间，但由于`game.addCharacterPack`本来就作用不大，故暂时这么改。

[Experimentalize] Guozhan Extension Interface.

---

game/game.js
mode/identity.js

将`game.import`的异步与最新的`lib.gnc`融合，可以直接用生成器函数做配置，而不需要调用`gnc.async`。
从另一个角度来说，在`game.import`时无法调用`lib.gnc`，故必然需要使用`gnc.await`。

[Purify] `game.import` fused of `lib.gnc`.

---

game/game.js

修复了`Promise.allSettled`在兼容版的polyfill中因数组长度过长而无法正常执行`Object.prototype.toString`导致阻塞，从而无法正常进行游戏。
> 顺带修复了异步加载后的一个小并发症。

[BugFix] 兼容版异步等待无限加载问题

---

game/game.js

lib.element.player.when:
链式创建一次性技能的api，使用者只需要关注技能的效果，而不是技能的本身。
例子: game.me.when('damageAfter').then(() => { player.draw(); }).then('player.draw(2);').popup('受伤摸牌').translation('技能名');
type:
```ts
interface when {
/**
* 传入技能filter。可传入多次
*/
filter(fun: (event: GameEvent, player: Player, name: string) => boolean): when;
/**
* 移除技能filter
*/
removeFilter(fun: (event: GameEvent, player: Player, name: string) => boolean): when;
/**
* 技能触发内容。一次为一个步骤step的内容。
* 
* 可以传入字符串。但是字符串不能出现大括号: {}
* 
* then里面的函数内容，和content是一样的，不会读取外部变量
*/
then(fun: string | ContentFuncByAll): when;
/**
* 触发技能时在玩家身上弹出的文字
* 
* 注意: popup和translation尽量一起用
*/
popup(str: string): when;
/**
* 修改技能名的翻译
* 
* 注意: popup和translation尽量一起用
*/
translation(translation: string): when;
/**
* 把一个对象的属性复制到创建的技能中
*/
assgin(obj: Object): when;
} …
```

在初始化(新手教程)之前的菜单不进行懒加载，另添加导出扩展的私货，以及修改分享扩展后的链接地址，player.when

---

game/game.js

- 去除读取`path.min`时因找不到文件而引发的报错，改为打印信息。

[Purify] `path`不再报错

---

game/game.js

- 参考`ai.basic.chooseCard`，在`ai.basic.chooseTarget`获取到`range`时就判断目标数已经足够，从而使得`selectTarget`为`[0, x]`时AI不再必须选择一名目标才能确定结果。

AI修复 | `chooseTarget`可以在“可空选”的情况下确定结果。 

---

game/game.js

- 增加`Player#setStorage<T>(name: string, value: T): T`，用于设定`player.storage[name]`的值
- 增加`Player#hasStorage(name: string): boolean`，用于判断是否存在`player.storage[name]`
- 增加`Player#initStorage<T, U>(name: string, value:T): U`，用于使用一个给定的初始值初始化`player.storage[name]`，当且仅当`player.storage[name]`不存在时将值给与`player.storage[name]`
- 增加`Player#updateStorage<T>(name: string, operation: (originValue: T) => T): T`，用于获取`player.storage[name]`并立即根据原值更新`player.storage[name]`
- 增加`Player#updateStorageAsnyc<T>(name: string, operation: (originValue: T) => Promise<T> | T): Promise<T>`，作为`Player#updateStorage<T>`的异步版本，可在回调函数中执行异步相关的操作
---
- 增加`Player#countExpansions(tag: string): number`，用于获取X区某一tag的牌的数量
- 增加`Player#hasExpansions(tag: string): boolean`，用于判断X区是否存在某一tag的牌

函数增加 | 一些跟`storage`有关的函数

---

game/game.js

- 现在`Event#setContent`在处理`lib.element.content`出错时会打印`lib.element.content`的内容，用于排查错误
> 目前没处理原有错误
- 现在`lib.init.parsex`可以接纳：
- 任意可被原来的`parsex`识别的字符串
- 任意可迭代对象(含有`Symbol.iterator`的对象)
- 带有`toString`方式的任意对象

[Bug] 兼容修复 | `Event#setContent`及`lib.init.parsex`接纳更多参数

---

game/game.js

- 现在`Player#hasStorage<T>(name: string, value: T): boolean`可以额外判断`player.storage[name]`是否为给定的值（或包含对应的值）
- 增加`Player#hasStorageAny<T>(name: string, values: T[]): boolean`、`Player#hasStorageAny<T>(name: string, ...values: T[]): boolean`、`Player#hasStorageAll<T>(name: string, values: T[])`和`Player#hasStorageAll<T>(name: string, ...values: T[])`，用于判断`player.storage[name]`的值是否存在`values`的值/包含`values`

[Enhancement] 函数增加 | 还是和`Storage`相关的函数

---

game/game.js

添加lib.init.jsSync，lib.init.reqSync，lib.init.jsonSync用于发起同步请求(addEventListener的load也是同步触发)，其只能在http/https协议或者打包好的客户端使用。
修改lib.init.req，支持传入'local:xx/yy'的本地路径去读取本地文件，限制如上。lib.init.reqSync也支持此写法。
lib.init.reqSync若没传入onload，那次函数将直接返回请求结果(字符串)。
优化HTMLDivElement.prototype.listenTransition的写法，执行一个时也会同时解除另外一个的后续执行
优化 window.onerror
拷打 Rintim

lib.init.jsSync，lib.init.reqSync，lib.init.jsonSync，change window.onerror change lib.init.req, change HTMLDivElement.prototype.listenTransition

---

character/refresh.js

- 移除`refresh.js`中 @mengxinzxz 额外上传的`wangyi`翻译
---
> 虽然没必要，但
> 总之由理电脑版不会再提升翻译重复

[Bug] 移除多余的翻译

---

game/codemirror.js
game/game.js
layout/default/codemirror.css
layout/default/menu.css

1.默认字体大小由继承于body的16px改为20px且根据zoom调整大小
2.抽离初始化CodeMirror代码
3.增加切换主题功能
4.增加编辑功能
5.修复一系列样式偏移的bug
6.※增加代码提示功能
7.魔改(几乎重构)了CodeMirror.js和CodeMirror.css

升级CodeMirror功能

---

game/game.js

- 修复兼容版不支持函数尾随逗号
- 补充`addNature`钩子的参数，使`game.addNature`和`hooks.addNature`的参数列表一致
- 将调用钩子的函数抽离成`game.callHook<T>(name: string, args: Parameters<T>): void`，现在可以直接用诸如`game.callHook("addNature",[...])`来调用`lib.hooks.addNature`里的所有函数，并自动判断执行时机。`args`的参数将被传入`lib.hooks`的函数当中。
---
> 懒得做语法分析了直接上结果
本次测试使用一扩展方便测试，代码如下：
```Javascript
game.import("extension",function(lib,game,ui,get,ai,_status){return {name:"钩子测试",content:function(config,pack){
game.addGroup("test2_group","试","测试2",{
color: [127,0,255, 1]
});
game.addNature("test_nature", "测试", {
color: [255,0,255, 1]
})
},precontent:function(){
game.addGroup("test1_group","测","测试1",{
color: [255,0,127, 1]
});
},config:{},help:{},package:{
character:{
character:{
"hook_test_a": ["none", "test1_group", 4, ["hook_test_gainCards"], []],
"hook_test_b": …
```

[Enhancement] 更新钩子相关代码

---

card/extra.js
card/guozhan.js
card/standard.js
card/yingbian.js
character/clan.js
character/ddd.js
character/extra.js
character/huicui.js
character/mobile.js
character/offline.js
character/refresh.js
character/sp.js
character/sp2.js
character/tw.js
character/yijiang.js
game/game.js
mode/boss.js

取消在 `Object.prototype` 上定义 `hasNature` 方法的隐患写法（暂且保留，且于下版本废除），改为用 `game.hasNature` 进行判断。
参数为 `(item, nature, player)`<ul><li>`item` 为要判断的卡牌或事件（不过伤害事件依然保留了 `hasNature` 方法），<li>`nature` 为要判断是否存在的属性，<li> `player` 为通过 `mod` 技影响 `nature` 判断的玩家对象。</ul>

将判断属性的方法改为`game.hasNature`

---

game/game.js

lib.announce.publish(key,object)  //推送一个对象给所有监听了key的订阅者。
lib.announce.subscribe(key,subscriber)  //订阅key相关的事件。
lib.announce.unsubscribe(key,subscriber)   ////取消对事件key的订阅，subscriber需要为上面lib.announce.subscribe返回的值。
使用范例：
甲扩展（如《千幻聆音》）在角色皮肤切换后，调用：
`lib.announce.publish("skinChange",{player:player,playerName:"zhangfei",originSkin:"image/xxx.jpg",currentSkin:"image/yyy.jpg"})`
乙扩展监听此skinChange事件，并修改自己扩展相关界面的图片：
`lib.announce.subscribe("skinChange",function(key,obj){
div.setBackgroundImage(obj.currentSkin);
});`

新增lib.announce库，使用订阅/发布模式，实现扩展间解耦调用。

---

game/game.js

- 现在`Player#hasHistory`的第二个参数`filter`拥有默认值`lib.filter.all`，目前可以直接`Player#hasHistory(name)`用来判断玩家是否发生过对应名字的事件

[Bug] 修复`Player#hasHistory`必须携带`filter`才能使用

---

game/game.js

- 将`get.nodeintro`中显示武将手牌数量的部分增加了手牌上限的信息
和距离获取以及标记信息显示一样，只是在点开武将的`nodeintro`时才会读取信息，故不会因为手牌上限的频繁切换而造成性能损失
---

[Enhancement] 在武将的`nodeintro`显示武将的手牌上限

---

game/game.js

- 在`game.trySkillAudio`和`ui.click.charactercard`中给技能的`audio`属性增添了一条新的分支。当满足以下条件时，会执行新分支的内容:
- `audio`属性不为字符串和数字
- `audio`属性为对象且拥有`type`和`files`属性
- `audio.type == "direct"`
- `audio.files`可以为`Object`和`Array`；当`audio.files`为`Object`且传入玩家信息时，会依次查看`player.name`, `player.name1`和`player.name2`是否在`audio.files`里，并读取最先存在的数据；反之当`audio.files`为Array时则直接顺序执行
- 最后随机播放`audio.files`的配音地址指向的文件（如果在`ui.click.charactercard`中则顺序播放）
- `audio.files`中的内容为任意可放到`game.playAudio`里的地址
---
- 可在多个技能中使用同一个配音文件，通过原始的方法实现了下面的操作:
> A技能拥有两个功能B和C，其中两条配音对应B，两条配音对应C，希望在点击A技能时能顺序播放B和C共4条配音，而B和C只播放对应的两条配音，且不想多出重复文件
- 能同时在一个技能里使用mp3, ogg, flac等多个格式
- 可将配音文件放在不同的文件夹下
- 能通过部分打包软件来维护扩展配音文件
- etc.
由于新分支位于判断是否为数字之后，故以往所有的“带配音技能”都不会走到新分支的判断，仅有无`audio`属性或`audio`属性不规范的技能才会绕过新分支，故可以认定性能不会因此受到太大影响 …

[Enhancement] 技能的配音文件可以直接给语音地址

---

game/game.js

1、`add`,`addArray`,`remove`,`removeArray`方法更改，以解决多参数问题（附赠的`everyInD`请当做没看到）
**此次更改涉及到返回值更改**
通过正则搜索以及询问绝大部分扩展作者(包括rintim,show-k等)，我了解到几乎不会有人用返回值，故作此更改，**但是还是请在更新公告中说明返回值改变的问题**
2、感谢Curpond@Curpond提供的`containsSome`,`containsAll`,`maxBy`,`minBy`方法，以简化部分需要包含关系或判断极值的问题
3、感谢钫酸酱@chen079提供的`unique`,`toUniqued`方法，以简化数组去重（因为有人不会用set解决）
4、此次为**联合pr**，不代表@kuangshen04的个人观点
5、此次pr已经发在群中进行测试过，暂未发现问题，**但不保证万无一失**，如果发现bug请在pr-branch尽早提出，尽量不要合并到本体之后进行猎巫行动

`Array.prototype`更改

---

game/game.js

这回真的是我pr了
1、支持audio直接输入路径，形如`audio:'card/male/sha(.mp3)'`，后缀可加可不加
2、支持形如`audio:['card/male/sha','tuxi']`这种格式，数组中可放置任意数量的路径或技能名，该示例实际效果为：在’突袭‘的两条语音和’杀‘的语音中随机播放一条
3、应寰宇星辰@universe-st要求，增加`audio:function(player){}`格式，但是不保证复杂情况的稳定性
4、audioname2现在支持所有audio的格式
5、注释掉的`index`参数本来是为charactercard的顺序播放准备的，但是@Rintim建议废弃，并提出有更好的方法
6、由于方法改为分析audio并输出路径数组，debug时可以根据注释掉的console.log来检查audio是否符合预期
7、由于完全覆盖了@Rintim在上次pr中添加的功能，且其未登陆正式版，故暂时废弃了`audio:Object`的写法
**在隔壁群测了两天才发的，但是还是请在合master之前再测试一遍（或做一遍code review）**

`trySkillAudio`究极大改

---

game/game.js

在addNature中，可以通过config传递特殊属性伤害音效。（目前暂时不支持多属性音效）
`
game.addNature('gold','金',{
audio:{
damage:{
gold:{ 
1:'../extension/XXXX/audio/jin_damage.mp3',
2:'../extension/XXXX/audio/jin_damage2.mp3',
}
},
sha:{
gold:{ 
male:'../extension/XXXX/audio/jinsha_male.mp3',
female:'../extension/XXXX/audio/jinsha_female.mp3',
}
}
}
});
`

增加属性伤害音效逻辑、属性杀音效逻辑

---

game/game.js

根据#507，初步对`ArrayContent`和`GeneratorContent`进行`debugger`支持。
**注意:** 由于不适用动态操作函数，目前无法通过`event.debugger()`进行调试操作，只能通过`yield code=>eval(code)`来调试。

支持额外类型Content的Debugger

---

card/extra.js
game/game.js

添加知情牌机制，用以辅助AI判断逻辑：
知情：若甲知道乙的手牌中包含这张牌，则认定甲是这张牌的知情人。
1、当牌被其他角色获得时，将添加原主为此牌的知情人。
2、当牌被展示或正面向上获取，或从判定区、弃牌堆、五谷丰登获取时，将添加所有角色（everyone）为此牌的知情人。
为card新增以下方法：
1、isKnownBy，判断角色是否对此牌的存在知情。
2、addKnower，为此牌增加知情人。
3、clearKnowers，清除此牌的知情人。
为game新增以下方法：
1、addCardKnower，批量为牌数组添加知情人。
2、clearCardKnowers，批量清除牌组的知情人。
为player新增以下方法：
1、getKnownCards，获取此角色被其他角色知情的牌。
2、hasKnownCards，判断此角色是否有被知情的牌。
3、isAllCardsKnown，判断此角色是否所有牌都被其他角色知情。
相关更新AI：
1、mayHaveSha、mayHaveShan添加知情逻辑。
2、lose事件后清除失去牌的知情信息。
3、gain事件后添加获得牌的知情信息。
4、观星时为牌堆顶、牌堆底的牌添加知情信息。
5、火攻时：若敌方所有牌我已知情，且敌方所有已有花色我都没有，则收益为0。
……其它AI待优化……

添加知情牌机制，辅助AI判断行动收益。

---

character/extra.js
game/game.js
mode/guozhan.js
mode/versus.js

修复`get.is.sameNature`、`get.is.differentNature`中遇到无属性牌时判断错误的问题。
添加`get.seatTranslation`，用于获取座次（N+1号位）翻译。
修复`ui.create.identityCard`创建的身份牌取消点击后所有按钮全暗的问题。
兼容测试通过。
（由于可能还有更多待修复的问题，所以此PR合并优先级还请尽量降低，或者最后一个合并。）

One More Thing.

---

game/game.js

为`lib.init.js`、`lib.init.css`、`lib.init.req`、`lib.init.json`和`lib.init.sheet`增加相应的`Promise`版本，用于异步函数直接`await`和部分情况的链式调用和对象传递。
所有添加方式的返回值均取自原有函数，除部分函数的返回值为对应函数所添加的DOM元素。

Add Promise-Async Methods for parts of `lib.init`

---

game/game.js

我们将`lib.handler`移动到了`game.globalEventHandlers`，以体现该功能对于游戏本身的影响，以及该功能更准确的用途。
顺带一提，我们找到了`lib.handler`代码中的部分问题，并于此次`Pull request`中修复了这些问题。
目前已确保该功能可以得到基本的执行。

Move `lib.handler` to fit position and fix its bugs.

---

game/game.js

我们将ui布局原有的`lib.init.sheet`转换成了`game.dynamicStyle`，改用存储选择器名的方式来通过避免频繁创建DOM减少性能损失。
> 话虽如此，频繁地`insertRule`和频繁创建dom的代价我们并不知晓，但目前的形式和虚拟DOM相似，后续可通过类似的优化来确保性能提升。

Transform `lib.init.sheet` to `game.dynamicStyle`

---

character/shenhua.js
character/standard.js
game/game.js

[实现此议题的异步函数](https://github.com/libccy/noname/issues/654)
注: async content中无法使用跳步(event.goto，event.redo)等函数。
注2: async content中不需要调用event.finish，直接使用return结束函数执行即可
使用示例:
```js
skill = {
// 二张直谏例子
async content(event, trigger, player){
await event.target.promises.equip(event.cards[0]);
game.log('装完了，还没摸牌')
await player.promises.draw();
},
}
skill = {
// 普通event转promise例子(郭嘉遗计)
async content(event, trigger, player){
// 事件函数(参数).toPromise().set(xx).setContent(yy);
await game.loseAsync({
gain_list: list,
giver: player,
animate: 'draw',
}).toPromise().setContent('gaincardMultiple');
},
}
```
新增类lib.element.GameEventPromise:
对于事件Promise化后，需要既能使用await等待事件完成，又需要在执行之前对事件进行配置。
所以这个类的实例集成了事件和Promise二者的所有属性，且Promise的原有属性无法被修改，一切对这个类实例的属性修改，删除，再配置等操作都会转发到事件对应的属性中。
使用示例：
使用toPromise()函数将普通事件转换为异步事件： …

增加异步content以及GameEvent#toPromise，郭嘉和二张作为测试

---

noname/init/cordova.js
noname/init/index.js

- 等待有效的测试
---
在一开始，无名杀手机端加载`cordova`的时机是`window.onload`，在拆分时也如此造做；由于`cordova`对于无名杀来说是手机端必然执行的代码，故跟手机端需要额外执行的代码均被放置在`cordovaReady`下。故此时的逻辑顺序是: 
- `await window.onload`
- `await cordovaReady()`
- `...(无名杀剩余逻辑代码)`
然而在考虑优化异步效率时，未考虑到扩展对`lib.path`的需求，将等待`window.onload`的时机提后到所有模块均加载完毕，故逻辑顺序变成了: 
- `window.onload(无名杀剩余逻辑代码)`
- `...`
- `await window.onload`
- ?
导致了存在扩展在`cordova`加载前便开始加载，从而使扩展无法正常读取到`lib.path`。
故我们首先将656行的`await waitDomLoad;`提前到550行，保证`window.onload`的内容一定位于扩展加载前执行完毕。
基于此，我们注意到，`cordova`的加载并不依赖`window.onload`，故我们令cordova的加载脱离`window.onload`

W.I.P | Fix a group of bugs of onload before cordova.

---

character/clan.js
character/collab.js
character/ddd.js
character/diy.js
character/extra.js
character/huicui.js
character/jsrg.js
character/mobile.js
character/offline.js
character/old.js
character/onlyOL.js
character/refresh.js
character/sb.js
character/shenhua.js
character/shiji.js
character/sp.js
character/sp2.js
character/standard.js
character/tw.js
character/xianding.js
character/xinghuoliaoyuan.js
character/yijiang.js
character/yingbian.js
mode/guozhan.js
mode/identity.js
noname/library/element/content.js
noname/library/element/gameEvent.js
noname/library/element/player.js

将**GameEvent#trigger的返回值**改为新触发的arrangeTrigger事件，从而可以在async content里面进行等待。
此外，添加**事件化版本**的”技能变化“事件，从而实现“获得技能时”和”失去技能时“的时机。
添加函数`Player#changeSkills([要获得的技能], [要失去的技能])`，用于进行技能的获得和移除。使用例：
```
//令player失去”激昂“和”魂姿“并获得“英姿”和“英魂”
player.changeSkills(['jiang', 'hunzi'], ['reyingzi', 'gzyinghun']);
```
changeSkills事件拥有四个标准的时机（changeSkillsBefore/changeSkillsBegin/changeSkillsEnd/changeSkillsAfter），且在触发时机前会自动去重。在该GameEvent中，`event.addSkill`为本次事件中，角色获得的技能；`event.removeSkill`为本次事件中，角色失去的技能。默认为先获得技能，后失去技能。
如果有特殊的需求（比如需要使用addAdditionalSkill，或者自行决定失去/获得技能的先后顺序），可以给changeSkills事件触发自定义的`$handle流程`。使用例：
```
//神孙权“驭衡”
const skills = player.additionalSkills.junkyuheng;
player.draw(skills.length);
player.changeSkills([],skills).set('$handle',(player,addSkills,removeSkills)=>{ …
```

[WIP] “获得/失去技能时”的时机

---

noname/get/is.js

原函数判断逻辑为
`card.isCard || !card.cards?.length`
错误，会将实体牌判断为虚拟牌。
将逻辑修改为
`!card.isCard || !card.cards?.length`
可以解决这个问题。
同时，原拼写vituralCard错误，修正为virtualCard，与libaray/element/player.js中的拼写相同。
由于get.is中关于虚拟牌、转化牌、实体牌的判断逻辑在项目中没有使用，因此不会在项目中造成兼容性问题。
如果考虑兼容扩展，可以定义别名。

fix：`get.is.vituralCard()`将实体牌判断为虚拟牌修复虚拟牌判断

---

character/sp2.js

当前版本逻辑中“义子”和“叛弑”是同一个技能，并且没有`charlotte`或者`locked`标签，导致可以被部分移除技能/技能失效效果影响。
现在将“义子”单独写成一个subSkill，原“慈孝”对“叛弑”的所有引用改为“义子”；“义子”同时赋予“叛弑”技能。从而试图修复这个问题。

fix：分离丁原的“义子”标记和“叛弑”技能

---

character/huicui.js
character/mobile.js
character/rank.js
character/sb.js
character/sp2.js
character/standard.js
character/tw.js
character/xianding.js
character/yijiang.js
game/pinyinjs.js
noname/get/index.js
noname/get/is.js

1. 杨奉、谋夏侯惇、谋高顺；
2. 因杨奉修改技能会去除转换技标签，新增 `zhuanhuanji2` 标签用于判别是否为转换技（如没有则继续判断 `zhuanhuanji`），新增 `get.is.zhuanhuanji` 函数；
3. 根据小道消息调整新杀曹爽〖渐专〗删除选项的概率。

杨奉、谋夏侯惇、谋高顺；调整转换技标签为可随时调整

---

character/diy.js
character/jsrg.js
character/refresh.js
character/standard.js
mode/guozhan.js
noname/game/index.js
noname/library/element/content.js
noname/library/element/gameEvent.js
noname/library/element/player.js
noname/library/index.js

- **logTarget现在生成的目标会自动传递给技能的content**
现在logTarget确定的“技能的目标角色”会自动传入技能content的event.targets中，而不需要重复调用。
- **将技能的cost选择和content执行分离，从而回避原本的含糊不清的情况。**
对于原本使用direct:true取消logSkill，然后在技能内部选择消耗，再logSkill的情况而言，虽然有效，但是难以区分“技能选择消耗的过程”和“技能本身的效果”，不是一件好事。
因此，我们决定将技能的cost和content分离（旧的写法仍然有效，不受影响）。使用例见张辽【突袭】：
```
tuxi:{
audio:2,
trigger:{player:'phaseDrawBegin1'},
filter(event,player){
return !event.numFixed;
},
//cost部分，选择技能的消耗
async cost(event, trigger, player){
let num = game.countPlayer(current => current != player && current.countCards('h') && get.attitude(player,current) <= 0);
let check = (num >= 2);
const {result} = await player.chooseTarget(get.prompt('tuxi'), '获得其他一至两名角色的各一张手牌', [1,2], (card, player, target) => {
return target.countCards('h') > 0 && player != target;
}, target => {
if …
```

分离技能的cost选择与content执行；允许在同一个时机内多次发动同一个技能

---

character/sb.js
character/standard.js

filter中player.hasSkill参数未囊括装备技能，需将参数arg3的值改为null
已修复：莺舞
待修复：史阿心授？

修复神典韦无法使用部分武器牌技能的bug

---

noname/library/element/content.js
noname/library/element/player.js

为`chooseToEnable`和`chooseToDisable`方法添加`source`参数，现在目标角色废除哪个装备栏由`source`对应玩家决定，若不存在`source`，则`source`默认为被废除装备栏的角色。

chooseToEnable和chooseToDisable方法添加source参数

---

game/pinyinjs.js

所有平台
如果英文武将名有空格资料卡会弹窗
先删除中文字符之外的所有字符（包括英文字母、数字、标点符号、空格和其他非中文字符），然后再查找多音字
通过
无需适配

fix：如果英文武将名有空格资料卡会弹窗

---

noname/library/init/index.js

手机更新失败，定位问题在如下行。
进入Req发现this作用域没绑，怎么能通过`this.reponseText`取到东西呢？
话说这问题好像好久了，今天终于找到空看一眼，下次修改时顺便也验一下移动端吧，多谢。

[bugfix][移动端更新报错问题] this作用域未绑定

---

noname/library/element/content.js
noname/library/element/gameEvent.js
noname/library/element/player.js
noname/library/index.js

全部
避免有人闲的没事回复/失去负数点体力；同时取消掉原本使用全局技能，屏蔽满血角色的体力回复事件的方法。
给recover事件和loseHp事件增加了filterStop，用于随时判断这些事件的当前数值是否小于0，并在事件本身的content内部进行判断。
扩大了filterStop的执行范围，在GameEventPromise.trigger中增加了一次filterStop的执行，避免在不恰当的时机清除tempSkill。
测了，暂时没问题。
对于那些直接修改recover和loseHp事件的content，从而实现回复/失去体力特效的扩展而言，该Pull Request会导致这些扩展产生bug。

recover事件和loseHp事件增加检验

---

card/standard.js
character/ddd.js

所有平台
修复[OL界王异；族王沦改晋势力；bugfix；还原部分无名杀彩蛋](https://github.com/libccy/noname/pull/1106/commits/2999b19b3f382c9b63628cbb3c8ce15f45ccf3e6)中针对3D于禁的修复问题以及群友反馈的“AI使用【决斗】后因手牌数减少而使用【无懈可击】”尝试修复
【决斗】的ai.result排除将【决斗】作为可能的【杀】的考量；
3D于禁【整军】用targets承接forResultTargets再进行后续操作
用【鼓舌】创造多人同时失去牌的时机检测

【决斗】AI修复，3D于禁【整军】修复

---

card/standard.js
character/mobile.js
character/shenhua.js
character/sp.js
character/sp2.js
character/xianding.js
character/yijiang.js

所有平台
吴懿对有八卦阵效果的角色发动【奔袭】时ai必然卡死
修复吴懿对有八卦阵效果的角色发动【奔袭】ai卡死的bug；
微调【杀】默认出闪ai；
为【八卦阵】默认ai增加专行判断；
删除本体中不严谨易出bug且多数情况下也无效的'unequip_ai'标签检测
见上
无需适配

bugfix，出闪ai微调

---

index.html
noname/ui/create/menu/pages/otherMenu.js
service-worker.js

电脑端和手机端
1.使import可以解析node内部模块
2.优化素材更新机制
1.使import可以解析node内部模块
**只能解析node内部自带的模块**
例如:
```js
import fs from 'node:fs';
```
2.优化素材更新机制，自动记录素材每一类的大小
浏览器控制台使用await import('node:fs/promises')
和点击更新素材按钮
import可以解析node内部模块部分无需扩展适配，但是需要电脑客户端适配，将我改的html代码粘贴过去到电脑客户端的html
更新素材机制部分，需要覆盖更新按钮的扩展跟进

使import可以解析node内部模块

---

noname/game/index.js
noname/get/index.js
noname/library/element/player.js

**PR受影响的平台**
所有
**诱因和背景**
globalskill问题由群友 @白银山幽灵 提出，多个玩家/技能提供相同的globalskill在移除其中一个时会导致全部失效
attaclTo问题由群友 @终日羽禁 提出，拼写错误，应该是attackTo而不是attaclTo
**PR描述**
globalskill方面：
- 为removeGlobalSkill添加了参数player，对接了player.js的调用。
attaclTo方面：
- 对接其他部分代码的attackTo，纠正原来的拼写错误。
**PR测试**
在本地运行测试无异常。
globalskill的测试结果达到预期
attackTo的测试结果达到预期
测试代码如下：
```javascript
// 测试globalskill问题
lib.skill.test_skill = {
forced: true,
global: 'test_skill2',
};
lib.skill.test_skill2 = {
forced: true,
trigger: {
global: 'phaseBegin',
},
content() {
player.say('持有技能test_skill2');
},
};
game.players.forEach(p =>
p.addTempSkill('test_skill', { player: 'phaseEnd' }));
// 测试结果：
// （环境：两人军争）
// 第一轮每个回合所有角色都会说话
// 第二轮不再说话
// 达到预期
// 测试attaclTo问题
lib.card.test_card = {
type: 'equip',
fullskin: true,
subtype: 'equip3',
enable: true, …
```

修复globalskill移除问题、attaclTo拼写错误

---

noname/init/polyfill.js

所有平台
这种写法的武将无剪影（无原画时）
若nameinfo[0]没有对应的剪影素材，则剪影全为male
通过
无需适配

fix: 若nameinfo[0]没有对应的剪影素材，则剪影全为male

---

character/huicui.js
character/jsrg.js
character/old.js
character/sb.js
character/shenhua.js
character/sp.js
character/tw.js
character/yingbian.js

所有平台
移除nzry_mingren的combo，因为谋卢植沿用此技能但有不为此combo的combo技能sbzhenliang；
继续补充技能combo；
国战禁用无限制变更势力的武将或技能
无需适配

国战禁用无限制变更势力的武将/技能，combo补充

---

character/extra.js
character/mobile.js
mode/versus.js

所有平台
同步手杀线上武将改动
<ul>
<li>将神鲁肃〖榻谟〗修改为手杀可以换一号位版，并添加对应FAQ；</li>
<li>解除对决→欢乐成双模式中带 `changeSeat` 标签的技能的禁用。</li>
</ul>
身份、对决、斗地主模式测试并无问题
无

神鲁肃榻谟修改；去除欢乐成双模式中换座位技能的禁用

---

card/standard.js
character/extra.js
character/huicui.js
character/mobile.js
character/shiji.js
character/sp.js
character/sp2.js

所有平台
[#677](https://github.com/libccy/noname/pull/677)AI计算乐不思蜀收益时分母为0
由于个人提的拆顺优化ai（找了几圈愣是没找到）导致经常不使用拆顺，数番测试仍未能探明原因
回滚拆顺ai.result，现在人机会正常拆顺了；
修复【乐不思蜀】ai.result；
【清严】bug修复；
标签补充
无需适配

回滚拆顺ai.result，bugfix，标签补充

---

character/ddd.js
character/huicui.js
character/jsrg.js
character/offline.js
character/old.js
character/sp.js

所有平台
发现部分技能描述显示问题
【朗怀】增加另一半描述；
【遁世】开局前不划掉基本牌名；
去掉【侠横】多余句号；
combo, neg标签补充
进入游戏查看

标签补充，部分技能描述修复

---

noname/game/index.js
noname/init/polyfill.js

所有平台
无名杀目前只支持相对地址的文件读取，但对`blob`和`http`等协议的需求却并不少见
由于无名杀的特性以及个人对无名杀的思考，仅仅对部分内容增添了`blob`的相关代码
为character[4]的武将图片增加独立的`img`前缀，同时保留原有的形式不变，供`blob`链接通过`img`前缀提供
一个简易的读取本地文件并创建Blob链接的函数：
```javascript
async function createURL(fileLink, type = "text/plain") {
let file = await game.promises.readFile(fileLink);
let blob = new Blob([file], { type });
let url = URL.createObjectURL(blob);
return url;
}
```
创建扩展：
```javascript
export let type = "extension";
export default async function () {
// 获取测试武将的Avatar和DieAudio，这里选用孙策的图片
let avatar = await createURL("image/character/sunce.jpg", "image/jpeg");
let dieAudio = await createURL("audio/die/sunce.mp3", "audio/mpeg");
// 获取测试技能的配音，这里直接用激昂的配音
let skillAudios = await Promise.all(
["jiang1", "jiang2"].map((name) => createURL(`audio/skill/${name}.mp3`, …
```

增加对Blob链接的部分支持

---

noname.js
noname/get/index.js

全部平台
在无名杀正式过渡到http协议前，无名杀的路径在不同端拥有不同的情况:
- 网页端: 除了`db`外，没任何可能
- 电脑端(electron): 和`node.js`保持一致
- 手机端(cordova): 需要使用`cordova`的`cordova-plugin-file`插件实现，有较为严格的限制
故之前的路径API基本如下:
- 网页端完全不考虑
- 使用`lib.assetURL + <relative path>`的形式，其中`lib.assetURL`的值为:
- 在网页端和电脑端为空字符串
- 在手机端为无名杀包的`externalApplicationStorageDirectory`里（也就是`Android/data/<app-id>/`）
现在无名杀即将踏入http协议，也早已用上了ES Module，故活用`import.meta.url`来提供路径理应被重视，`URL`也理应成为路径的主要构成
然而由于之前的API混乱且针对多端有不同的情况，故需要提供函数，来方便提供调用旧API的情况
增加`get.relativePath(url: URL, addAssetURL: boolean = false): string`函数，该函数会将URL转换成相对于无名杀根目录的路径，具体算法基于原有路径的经验编写
该函数的参数解释如下:
- `url: URL`: 需要转换的URL对象
- `addAssetURL: boolean = false`: 是否需要在函数内加上`lib.assetURL`，默认为`false`，当为`true`时会在协议为`file`时增加`lib.assetURL`
该函数的用法如下：
```javascript
// 当前文件以"noname/get/index.js"举例
let parsedPath = …
```

提供新函数，使基于`import.meta.url`的URL转换为无名杀的相对路径

---

noname/get/index.js
noname/library/init/index.js
noname/library/init/promises.js

全部平台
无名杀过多基础设施都会自行解析`ext:`和`db:`等前缀，且不满足则遵循惯用法解析；路径
但随着无名杀步入http时代，我们应该让所有能解析的URL都得到解析
增加`lib.init.parseResourceAddress(link: string | URL, defaultHandle?: (item: string) => string, forceLoadAsDataUrl?: boolean): Promise<URL>`函数，其中参数的解释如下：
- `link`: 需要解析的路径
- `defaultHandle`: 在给定路径不符合可用情况（或基于无名杀相关默认情况）时，处理路径的函数，返回的路径应是相对于根目录的相对路径，默认为`null`，当且仅当无法解析成`URL`时会调用该回调
- `forceLoadAsDataUrl`: 是否将资源加载为[Data URL](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/Data_URLs)，默认为`false`
考虑到后续无名杀的发展，故返回值为URL，可通过`result.href`获取到原始路径字符串，再可通过`get.relativePath`获取相对路径，但请确保该路径可用于`get.relativePath`
`defaultHandle`用于兼容无名杀以往的惯用法，如果确认传入的`link`一定为URL，可将`defaultHandle`设置为`null`
同时为了一些额外需求，增加转换成Data URL的选择
目前有个关于`db:`的问题，个人不确定无名杀数据库中会通过该函数的数据库链接是否都是Data …

增加通用性解析寻址函数

---

noname/game/index.js
noname/get/index.js
noname/library/element/character.js
noname/library/element/content.js
noname/ui/click/index.js

现在die audio支持几乎所有skill audio的格式。
废弃Character类的die_audio写法（控制台弹出警告），现在可以通过多个die:来达到相同效果。
播放死亡语音现在被封装为了game.tryDieAudio，与game.trySkillAudio对应。

parseDieTextMap功能升级

---

character/shenhua/skill.js
noname/ui/create/index.js

所有
**诗笺喵的任务喵**
shenhua step转async
**Curpond的任务喵**
修复自由选将搜索输入框的bug，以及追加placeholder喵
详情 issue [#1350](https://github.com/libccy/noname/issues/1350)
更改了 新袁术、张绣、旧陈到、严颜、王平、陆绩 这六个角色的技能喵
（其实还有两个技能，但是那两个技能没人用白改了（悲））
**追加**
修复自由选将搜索输入框的bug，以及追加placeholder喵
全部都使用了一遍技能喵
（那两个没有人用的技能没有测试哦，不过看了一下没有问题喵）
**追加**
测试了按键a和placeholder的显示没有问题
原本的enter响应也没有问题喵
无

step转async：新袁术、张绣、旧陈到、严颜、王平、陆绩；修复自由选将搜索输入框的Bug

---

game/entry.js
node_modules/@types/noname-typings/cordova-plugin-dialogs.d.ts
noname/init/cordova.js

所有
[为新客户端的导入离线包/完整包功能提前做适配](https://github.com/libccy/noname/commit/cf6ec448a9c50943d186db0c339353223dd0fef1)
[优化升级协议时的观感](https://github.com/libccy/noname/commit/79d833e15a0069b2b21da67c6982ee50858b31cf)
[修改处理网页参数后重启的路径](https://github.com/libccy/noname/commit/71afbe7028055ee884adb8fd0f29a2eb35c96f79)
导入离线包后也加了弹窗提示
安卓升级协议时提供dialog提示
修改处理网页参数后重启的路径
无

为新客户端的导入离线包/完整包功能提前做适配、优化升级协议时的观感、修改处理网页参数后重启的路径

---

character/standard/skill.js
character/standard/sort.js
character/standard/translate.js

所有平台
无
fix：将2024标准包修正为四象封印·少阴、醮影修复
（虽然个人觉得拆出来比较好，但标准版强度武将放标准包里也说得过去）
通过
无需适配

fix：将2024标准包修正为四象封印·少阴、醮影修复

---

noname/game/index.js
noname/get/audio.js
noname/get/index.js

对音频播放的描述字段进行了整合，以下是使用格式细节：
📝 注意事项: 当你希望为角色添加死亡语音时，你可以直接为Character实例的dieAudios属性赋值，或在数组形式中填写多个"die:xxx"来达到相同效果。例如`"die:ext:无名扩展/audio/die:true"`在转为Character实例时会转化为`dieAudios:["ext:无名扩展/audio/die:true"]`
- `false`: 不播放语音。
- `true`: 播放默认路径下（`skill/` 或 `die/`）与技能名或角色名一致的音频。例如 `wusheng: {audio: true}`，将播放 `["skill/wusheng.mp3"]`。
- 数字: 表示播放默认路径下以数字做后缀的音频文件。例如 `wusheng: {audio: 2}`，将播放 `["skill/wusheng1.mp3", "skill/wusheng2.mp3"]`。
- 字符串（引用）: 播放对应引用技能或角色的音频。例如 `wusheng: {audio: "paoxiao"}`（假定 `paoxiao: {audio: 2}`），将播放 `["skill/paoxiao1.mp3", "skill/paoxiao2.mp3"]`。
- 路径: 直接按指定的音频路径播放。例如 `wusheng: {audio: "ext:无名扩展/audio/wusheng.mp3"}`，将播放指定的 `["ext:无名扩展/audio/wusheng.mp3"]`。
- 路径 + true: 播放指定路径下与技能名或角色名一致的音频。例如 `wusheng: {audio: "ext:无名扩展/audio:true:mp3"}`，将播放 …

R.I.P. (先合)使用get.Audio整合parse audio api 

---

mode/boss.js

所有平台
诸神降临扩展中的祭风卧龙体力上限异常，为零而非无限大。
把Infinity标签换成了字符串
测过了，没问题
不需要

修复诸神降临扩展祭风卧龙体力上限异常的问题

---

noname/init/index.js
noname/util/initRealms.js
noname/util/sandbox.js
noname/util/security.js

所有
**追加**
有针对Safari（苹果）的内容
**追加**
所有
之前的情况还是可能被渗透，选择简化代码牺牲微小的兼容性来妥协安全性
**追加**
应狂神的要求，追加对于调试模式下禁用沙盒的功能
可能由于对于苹果的不兼容性，对苹果禁用沙盒功能（另外苹果的安全本身也很抗打）
（上面两种禁用沙盒依然保留防注入的功能）
**追加**
因萌喵说eruda载入有问题，特地对eruda进行优化
简化一下eval，用最朴实的方法来适配大部分情况
牺牲了沙盒启用的情况下，在eval、new function、parsex等编译代码内（沙盒代码内），当再嵌套使用eval执行代码时的部分兼容性，以此来提高安全性（对于此类情况下eval最常规的使用还是做了适配，但是过于阴间的写法放弃兼容了）
（另外之前没有关闭全模式沙盒哦现在补一下_(:з」∠)_）
**追加**
调整了沙盒的载入顺序，并先确认调试模式与苹果设备再决定是否载入
**追加**
让封送代理的空白对象行为与目标对象保持一致以适应js严格的代理检查（适配eruda的用法）
添加hasInstance的封送映射，确保instanceof正常工作（适配eruda的用法）
新代码影响了游戏内控制台，通过控制台执行了多条代码确认工作正常
**追加**
调试模式可以影响沙盒的载入，测试通过
苹果的判断依赖于```get.is.safari()```，暂未测试，但是如果```get.is.safari()```在```boot```中正常工作那么应该与调试模式的效果相同
**追加**
对于eruda的载入和基本使用已经在电脑与安卓上测试完毕
暂无
**追加**
暂无

补充一个sandbox的问题；同时为调试模式和苹果设备放宽；适配eruda

---

character/extra/skill.js
character/yingbian/skill.js
noname/get/index.js

所有平台
以神典韦的〖挈挟〗作为例子，某些扩展中存在类似于下面的技能描述：
`①每回合每个字数限一次，你可将一张手牌作为与其字数相同、牌名不同的基本、装备、普通锦囊牌（【<a style='color:#FF0000' href="javascript:get.sbzz_daskillTips('①不能以此法转换为赠物<br/>②以此法使用的装备牌会改变名字，进入手牌区时恢复<br/>③装备牌印装备牌会同时拥有两牌的技能，加一、减一、武器的距离效果并不算技能</i> </b><br/>④注意：失去牌的效果，因为牌名改变所以不会触发，拓展卡牌失去效果如果写的代码不检查牌名的话就会生效，顺带一提，专属卡牌【刀】的失去效果也可以触发<br/><br/><b>专属卡牌：【刀】</b><br/>①若此牌的实体牌为【杀】则视为武器；【闪】则视为防具；【桃】则视为防御马；【酒】则视为进攻马。均不是，视为宝物<br/>②失去此牌时令【摘铸】已使用的最大的字数视为未使用过，然后可以令一名其他角色随机弃置两张牌，不足则全弃并视为对其使用一张【杀】','0');">印卡规则</a>】）使用或打出。②准备阶段，你摸2+2x张牌（x为你的体力上限减手牌数，至少为0、至多为2）然后获得装备区中所有牌。`
此技能描述实际显示为：
`①每回合每个字数限一次，你可将一张手牌作为与其字数相同、牌名不同的基本、装备、普通锦囊牌（【印卡规则】）使用或打出。②准备阶段，你摸2+2x张牌（x为你的体力上限减手牌数，至少为0、至多为2）然后获得装备区中所有牌。`
按照〖挈挟〗原先的筛选方法会将此技能误认为含有“【杀】”的描述，尽管实际显示的文本中并没有。
添加新函数`get.plainText`以将HTML代码转换为纯文本，并应用该函数到〖博览〗、〖挈挟〗的字段筛选机制中。 …

优化〖博览〗、〖挈挟〗的字段筛选机制

---

noname/game/index.js
noname/library/element/content.js

所有平台
因现本体存在很多于subSkill中的chooseButton+backup类技能，这些技能的sourceSkill仅能定位至此子技能，故而对所有未写sourceSkill的子技能默认赋予此属性，并对`chooseToUse`和`chooseToRespond`函数进行修改，使得能读取至多两层sourceSkill（反正也读不到第三层）
已测试已通过
修改了`game.finishSkill`和`chooseToUse`、`chooseToRespond`（多为后两者）的扩展需要进行适配

适配寻找subSkill中chooseButton+backup类技能的源头技能

---

character/shenhua/skill.js
node_modules/@types/noname-typings/nonameModules/noname/get/index.d.ts
node_modules/@types/noname-typings/nonameModules/noname/library/element/player.d.ts
node_modules/@types/noname-typings/nonameModules/noname/status/index.d.ts
node_modules/@types/noname-typings/nonameModules/noname/util/error.d.ts
node_modules/@types/noname-typings/nonameModules/noname/util/sandbox.d.ts
noname/game/index.js
noname/init/index.js
noname/status/index.js
noname/ui/create/menu/pages/exetensionMenu.js
service-worker.js

无
game.resume/resume2函数对async event的兼容判断
修复通过server.exe启动的网页端创建扩展不保存为文件和编辑武将图片不显示的bug
game.resume/resume2函数对async event的兼容判断
修复ServiceWorkerGlobalScope类型提示失效的问题
跟进typings
修复通过server.exe启动的网页端创建扩展不保存为文件和编辑武将图片不显示的bug
[解决了这个issue](https://github.com/libccy/noname/issues/1346)
无
无

game.resume/resume2函数对async event的兼容判断,修复通过server.exe启动的网页端创建扩展不保存为文件和编辑武将图片不显示的bug

---

layout/default/layout.css

手机端
全面屏右上角剩余牌数显示不全
调整只影响手机端的.touchinfo.right样式
打开游戏肉眼观察
无需适配

适当左移“显示剩余牌数"以支持全面屏手机完整显示

---

noname/get/index.js

所有
旧的函数不支持解构参数
重构了清洗函数，让它可以支持解构参数喵
* 多种函数头与函数体
* 解构参数与上下文关键字
* 抽象的参数默认值
已通过函数格式测试
无

bugfix: 修正pureFunctionStr，可以接受解构参数

---

noname/get/index.js
noname/util/sandbox.js

所有
问题是@PZ157报告的喵，因为导致了他的扩展联机出现错误_(:з」∠)_
因为js的奇怪限制，当函数出现参数默认值时，函数内不能标注"use strict"
让沙盒额外提供了接口来处理沙盒启用时的函数清洗
在新的版本中测试@PZ157的联机扩展不再出现问题，测试通过
暂无

bugfix: 修复因为复杂参数不能使用"use strict"导致沙盒和函数清洗的冲突问题

---

game/game.js

android
似乎部分客户端读取不到`noname-compatible.js`，故在此做个`fallback`
在`import("../noname-compatible.js")`失败后自行尝试读取需要的东西
没安卓端，但电脑端和网页端能跑，按理说没问题

修复安卓客户端读不到`noname-compatible`的问题

---

character/collab/character.js
character/gujian.js
character/huicui/skill.js
character/key/character.js
character/mobile/character.js
character/sb/character.js
character/sp/character.js
character/swd.js
character/xiake.js
character/xianjian.js
character/yijiang/character.js
character/yxs.js
noname/get/index.js

所有平台
优化【护关】ai；
修复部分姓名；
适配部分轩辕剑、古剑奇谭、仙剑奇侠传武将姓名；
注释xiake.js中一个不存在对应技能的武将；
删除非联机武将包中一个没有对应技能、info和简介的武将
无需适配

优化【护关】ai，修复部分姓名

---

game/entry.js
noname.js
noname/init/index.js
noname/init/onload.js

Android由理版
有人反应，通过由理版打开扩展压缩包导入扩展，会提示已导入完成，文件也存在，但进入游戏，并没有正常导入
调整了一下加载顺序，现在导入扩展将必然等待`game.saveConfig`完毕才重启
使用由理兼容版测试
最初的状态:
通过由理版导入扩展:
导入后的状态，可以看到扩展存在:
无需适配，除非用了之前导致的一些未知特性，因为更改了加载逻辑
> 不要问啥特性，因为我也不知道

修复由理版导入扩展无法在扩展列表显示的问题

---

character/clan/skill.js
character/ddd/skill.js
character/diy/skill.js
character/extra/skill.js
character/huicui/skill.js
character/key/skill.js
character/mobile/skill.js
character/newjiang/skill.js
character/offline/skill.js
character/onlyOL/skill.js
character/refresh/skill.js
character/shenhua/skill.js
character/shiji/skill.js
character/sp/skill.js
character/sp2/skill.js
character/tw/skill.js
character/xianding/skill.js
character/xinghuoliaoyuan/skill.js
character/yijiang/skill.js
character/yingbian/skill.js
mode/guozhan.js
noname/library/element/content.js
noname/library/element/player.js
noname/library/index.js

所有平台
测试其他bug时遇到的
将本因写在第三个参数位置的传参（false Player）修正；
修复部分错误写法导致的“普通锦囊牌”“锦囊牌”错用的问题；
为部分明确在手牌中且有player的get.type添加第三个参数player；
其他琐碎调整
请检查您扩展中的get.type(card, method, player)和get.type2(card, player)函数传参是否正确：
1、get.type(card, method, player)
card: 所检测卡牌，可以是字符串，不得为空
method: 若为"trick"，对于延时锦囊牌会返回"trick"，否则返回"delay"
player: 持有者，用于经过诸如〖红颜〗〖武魂〗这种Mod技能修改，不为Player则使用_status.event.player，为false则不检测Mod
2、get.type2(card, player)
等价为get.type(card, "trick", player)，普通锦囊和延时锦囊都会返回"trick"

修复本体中所有错误传参的get.type

---

README.md

将“内核版本大于等于77”修改为“内核版本大于等于85”
所有平台
在v1.10.14中，无名杀的版本的最低内核需求已经从Chromium 77升级到Chromium 85，但是README.md中相关描述仍为“内核版本大于等于77”，尚未更新。
将README.md中的“内核版本大于等于77”修改为“内核版本大于等于85”
仅修改README.md中的一行字，对游戏无影响。
仅修改README.md中的一行字，不需要额外适配。
-`[x]`我已经进行了充足的测试，且现有的测试都已通过
-`[x]`我没有把该PR提交到`master`分支
-`[x]`如果此次PR中添加了新的武将，则我已在`character/rank.js`中添加对应的武将强度评级，并对双人武将/复姓武将添加`name:xxx`的参数
-`[x]`如果此次PR中添加了新的语音文件，则我已在`lib.translate`中加入语音文件的文字台词
-`[x]`如果此次PR涉及到新功能的添加，我已在`PR描述`中写入详细文档
-`[x]`如果此次PR需要扩展跟进，我已在`扩展适配`中写入详细文档
-`[x]`如果这个PR解决了一个issue，我在`诱因和背景`中明确链接到该issue
-`[x]`我保证该PR中没有随意修改换行符等内容，没有制造出大量的Diff
-`[x]`我保证该PR遵循项目中`.editorconfig`、`eslint.config.mjs`和`prettier.config.mjs`所规定的代码样式，并且已经通过`prettier`格式化过代码

将README.md中的“内核版本大于等于77”修改为“内核版本大于等于85”

---

character/extra/skill.js
mode/single.js
noname/library/element/player.js
noname/library/index.js

所有平台
1.新增转化装备所导致的单独装备栏错位问题和空位装备栏失效问题
2.三个月前画的点将单挑的饼
3.神黄忠bugfix
1.修复转化/虚拟装备错位bug
2.修复现装备直接置入`player.node.equips`导致的空位装备栏错位bug
3.点将单挑模式开放单/双/任选单双将，取消点将单挑模式中AI禁选对将池的限制
4.修复神黄忠没有“赤”标记且满血时可发动【赤刃】的bug
测了，最终效果无误，但为了解决方法二故每次执行此函数均为所有`player.node.equips`的元素进行重新排列，故会有闪烁显示
需要覆盖$handleEquipChange的扩展进行适配

$handleEquipChange、神黄忠效果修复；点将单挑模式开放单/双/任选单双将

---

card/yingbian.js
character/clan/skill.js
character/extra/skill.js
character/jsrg/skill.js
character/mobile/skill.js
character/newjiang/skill.js
character/sb/skill.js
character/shiji/skill.js
character/sp/skill.js
character/tw/skill.js
character/yijiang/skill.js
mode/guozhan.js

所有平台
bug反馈
1.使用@AstralBarrage的`logAudio`和昨日提的`logSkill`修改，继续修改部分效果不同触发配音不同的技能的写法
2.修复OL陆凯【玄注】可印多目标锦囊牌的bug
3.修复族王浑【抚循】使用的基本牌有次数限制的bug
4.修复国战晋司马懿【骤霆】刷新bug
5.修复装备【天机图】后只能弃置【天机图】的bug
能跑
无

继续不同效果触发技不同配音修改；bugfix

---

game/generateChanged.js

无
由于一些测试需求，故一般会在项目仓库中放一些扩展，这些扩展并不期望被打包，然而打包脚本依然会将这些扩展打包进整合包中
对遍历`extension`目录的地方进行筛选，只考虑遍历无名杀自带的扩展
经过测试，可以看到`extension`目录下存在除自带扩展以外的扩展，而打包的包并未包含非自带扩展
无需适配

使打包脚本不会打包非官方扩展

---

noname/library/element/content.js

所有平台
由 #1679 提出，使用`moveCard`移动判定牌会出现有动画无逻辑的情况，该情况由于`moveCard`只将判定牌的`card`传给了`addJudge`，然而`addJudge`因为转向`addVirtualJudge`需要将实体牌也传入进去，所以本质上相当于移动了国王的新牌，故无事发生；由于动画重点在于vcard而非cards，故动画无明显问题
在`moveCard`中，将`card.cards`传入给`addJudge`
顺带修了 *指装备区为判定区*
重复杨彪【让节】移动判定区的牌
可以看到判定区的牌被正常移动
无需适配，除非改了`moveCard`

修复判定牌无法移动的情况 (#1679)

---

noname/get/index.js
noname/library/element/content.js
noname/library/element/player.js

无
尝试解决转化装备牌的非1转1遗留问题
修复武将信息页仍然获取`Player.getCards('e')`而非`Player.getVCards('e')`的bug
非1转1装备牌均同1转1显示为一张，`Player.getCards('e')`受此影响，获取的牌也均为转化后的牌（类别为`card`而非`vcard`）
非1转1装备牌作为一张牌的整体，仅能共同失去
修复武将信息页仍然获取`Player.getCards('e')`而非`Player.getVCards('e')`的bug，并进行了上述适配
测了大部分拆顺失的情况，**目前**一切正常
修改了'lib.element.content.lose'/'lib.element.content.gain'/'lib.element.player.$addVirtualEquip'的UI类扩展

转化装备多转一修复，提前准备转化判定多转一

---

noname/get/index.js
noname/library/element/content.js
noname/library/element/player.js

无
针对昨天的非1转1装备区修改的补充修改
兼容上个版本的lose的实体卡传入写法，es属性改为传入实体牌
更改`lib.element.player.$addVirtualEquip`的写法，使得存在废除装备栏的装备区卡牌变更不再会闪烁
修改武将信息页装备区写法
上述测试通过，仍需进一步测试
更改了更改`lib.element.content.lose`或`lib.element.player.$addVirtualEquip`的UI类扩展

非1转1装备区继续bugfix

---

noname/library/element/player.js

无
因`lib.element.player.$addVirtualEquip`现在装入的均为单一卡牌，故将`lib.element.player.$handleEquipChange`调整为v1.10.13版本以减少装备区显示刷新次数
鬼神易反馈的uninit重置vcardsMap问题
`lib.element.player.$handleEquipChange`写法回调
`lib.element.player.uninit`取消`Player.vcardsMap`属性重置
目前未测试出问题，装备区修改/优化仍需进一步测试
无

$handleEquipChange写法回调；uninit取消vcardsMap属性重置

---

layout/others/dialog.css
noname/game/index.js
noname/library/element/dialog.js

修复移动动画被遮挡问题，并让样式和原来的尽量一致

---

card/extra.js
card/standard.js
character/extra/skill.js
character/refresh/skill.js
node_modules/@types/noname-typings/Skill.d.ts
noname/get/index.js

无
吧友、群友&好友反馈
见commits标题。
此次修复了人机未装备连弩时因次数上限不足贸然酒杀的问题；
将”还能使用几张【杀】“放至order内判断；
暂时注释掉了result中考虑”只能杀一次“的前提；
拓展了info.ai.canLink函数返回值，计算传导伤害时info.ai.result下面的函数将得到”{ source: target }“为基础模板的传参isLink。isLink.source即为伤害传导的起点目标，以便于后续计算
现支持将该函数的返回值传入到计算传导收益中的get.effect(arguments)的第五个参数（isLink）了
具体案例请参看lib.card.sha.ai.canLink（返回值）和lib.card.sha.ai.result.target（isLink参数）
若无对应的info.ai.canLink函数，则isLink = { source: target }，其中target为伤害传导的起点
交给群友测试了
无

【酒】、属性【杀】传导ai再修；bugfix

---

extension/boss/extension.js
noname/game/index.js
noname/library/index.js

无
由于当初的扩展包改变过于激进，有些细节部分并未考虑，导致部分翻译为空
将`诸神降临`的武将包去除前缀
将`game.addCharacterPack`和`game.addCardPack`的前缀去除
为`lib.cardPack`提供去除`mode_extension_`前缀的Proxy
将`诸神降临`打开后，武将界面的名称正常
此处的`渣作集合`扩展用的是`game.addCharacterPack`添加的武将包，此时也正常显示
无需适配，但由于`lib.translate`不确定应不应该套层Proxy，故如果直接往`lib.characterPack`/`lib.cardPack`和`lib.translate`添加武将包/卡牌包信息，则仍然会出现翻译问题。

修复一些武将包前缀去除的问题

---

character/jsrg/skill.js
noname/library/element/content.js
noname/library/element/dialog.js

无
你说得对，但是本PR是由打完复活赛后的萌新（转型中）自主研发的一项全新的开放式议事流程，议事发生在一个叫做《无名杀》的游戏对局之中。在这里，被选中的人将被授予选牌能力，导引票选之力。你将扮演一名威震华夏的名将或历史角落的无名小卒，在自由的游戏对局中邂逅技能各异机制独特的武将，和他们一起开展议事，引出最后的议事结果。
修改江山如故的六个议事技能的非黑即红技能写法
若`lib.element.content.chooseToDebate`中赋予`event.debateIgnore`属性为`false`，则依据大家议事结果中颜色唯一最多的为结果（dialog显示为红色一行，黑色一行，若有其他意见则开启第三行并放入其中）；否则只统计红色和黑色的议事结果，且其余意见作废（dialog显示为所有角色的议事情卡牌放在同一个button之中）
为`lib.element.dialog.addNewRow`添加对非`string`元素的`_custom`接口
测了，十分甚至九分能跑的动
无

优化议事机制显示，增加两套议事结果流程

---

character/sb/skill.js
noname/game/check.js
noname/game/index.js
noname/get/index.js
noname/library/element/content.js

无
添加主动技能可以直接通过添加`deadTarget`和`includeOut`实现选择阵亡角色和Mamba out的角色
修改获取可选角色的逻辑，增添技能的`deadTarget`和`includeOut`检测
修改谋曹丕【行殇】选项五的写法作为首例
代码和我至少有一个能跑
修改了`game.check`和`game.uncheck`的扩展

主动技能的deadTarget和includeOut属性使用

---

character/clan/skill.js
character/diy/skill.js
character/extra/skill.js
character/mobile/skill.js
character/refresh/skill.js
character/shenhua/skill.js
character/sp/skill.js
character/xianding/skill.js
character/yijiang/skill.js

因为第一批技能幼龄化的过程中，删除了技能原有的mark,只保留了tip.
讨论决定，将tip定位为辅助标记。还是以mark为主，tip针对需要醒目提示的关键信息，增强玩家的游戏体验，不能替代原有的mark的地位。
后面会在原有mark的基础上逐步增加tip,以增加玩家的游戏体验，即使关掉tip，也不会对玩家造成影响。

将第一批幼龄化的技能恢复为原来的标记

---

card/extra.js
card/guozhan.js
card/hearth.js
card/swd.js
card/xianxia.js
card/yunchou.js
character/mobile/card.js
noname/init/onload.js

无
群友反馈
临时修复新建牌堆的一个bug，**但未能修复**添加属性杀不显示对应属性的问题；
为能造成属性伤害的卡牌增补了cardnature（目前只会在game.createCard里调用）；
调整了【火山】【浮雷】等属性伤害延时锦囊的tag
无
无

临时修复新建牌堆的一个bug；非杀卡牌属性调整

---

character/extra/skill.js
character/jsrg/skill.js
character/sixiang/skill.js
character/sp/skill.js
character/tw/skill.js
character/xianding/skill.js
noname/get/index.js
noname/library/element/card.js
noname/library/index.js

添加new Map类型`lib.numstrList`，存储特定点数的扑克牌花色显示
修改`get.strNumber`和`get.numString`函数适配`lib.numstrList`，函数见下
```
/**
* 返回数字在扑克牌中的表示形式
* @param { number } num
* @param { boolean } [forced] 未获取点数字母对应元素时是否返回字符串格式
* @returns { string }
*/
strNumber(num, forced) {
if (typeof num !== "number") return;
let result = lib.numstrList.get(num);
if (result === undefined && forced) result = num.toString();
return result;
}
/**
* 返回扑克牌中的表示形式对应的数字
* @param { string } str
* @param { boolean } [forced] 未获取字母点数对应元素时是否返回数字格式
* @returns { number }
*/
numString(str, forced) {
if (typeof str !== "string") return;
let result = lib.numstrList.entries().reduce((map, list) => {
map[list[1]] = list[0];
return map;
}, {})[str];
if (result === undefined && forced) result = parseInt(str);
return result;
}
``` …

扑克牌点数接口开放，简化繁琐的特定点数列举

---

node_modules/@types/noname-typings/Skill.d.ts
noname/library/element/content.js

无
动态usable内容补充
见标题
我和无名杀有一个能跑
无

usable添加类别注释；触发技支持非number的usable类型

---

game/game.js

Linux
判断__dirname的路径没有考虑路径分隔符和Windows不同导致修改失败

修复Linux下的路径判断

---

character/collab/skill.js

无
给别的武将做自定义时间的倒计时，参考离骚的实现的时候，发现即使回答错误也会结束抢答，就顺便修一下。
> 这些角色须同时回答《离骚》的句段填空（抢答题，一名角色回答正确后结束答题）
根据技能描述，如果一名角色答错，另一名角色仍可以在倒计时结束之前进行作答（从[作者使用`Promise.any`而非`Promise.race`](https://github.com/libccy/noname/blob/e18a8256e01ab1357e4c7472349dceb3d0aa1a3a/character/collab/skill.js#L1079C11-L1079C22)中也可基本看出此意图）。
因此，从原先的[只要玩家回答，就兑现Promise](https://github.com/libccy/noname/blob/e18a8256e01ab1357e4c7472349dceb3d0aa1a3a/character/collab/skill.js#L1065)，改为[仅在玩家答对时兑现](https://github.com/bacz00/noname/blob/8e616ae7bd3aab8d925d5e1fef690fc36d0fd58b/character/collab/skill.js#L1429)，[否则拒绝Promise](https://github.com/bacz00/noname/blob/8e616ae7bd3aab8d925d5e1fef690fc36d0fd58b/character/collab/skill.js#L1435)。
测试两名玩家分别答对/答错/超时的各种组合，均为正常。（至少和我理解的技能描述一样）
无

修复：【离骚】中玩家回答错误也会结束抢答

---

character/clan/skill.js
character/collab/skill.js
character/mobile/skill.js
character/onlyOL/skill.js
character/sp/skill.js
mode/guozhan.js

公元1103年-南宋
群友反馈
修复`mode/guozhan.js`中的丁奉【短兵】和吕范【调度】的`get content`的bug，并删除此文件中所有可以删除的`: function `
修复卫青【北进】无次数限制的卡牌结算异常的bug
修复族王沈【岸然】摸牌触发额外结算可能会使得卡牌可使用的bug和失去不可使用卡牌效果的时机bug
更正势太史慈【战烈】四选项的触发结算
测了，能跑
无

bugfix；国战去除": function "

---

character/mobile/skill.js
noname/library/element/GameEvent/compilers/ArrayCompiler.js
noname/library/element/GameEvent/compilers/ArrayCompiler.ts
noname/library/element/GameEvent/compilers/YieldCompiler.js
noname/library/element/GameEvent/compilers/YieldCompiler.ts

无
一开始，人们以为是`Yield Content`的问题
由于人人喜爱`Async Content`，`Yield Content`没人在意，故计划被`Async Content`夺舍
虽然现在已经还`Yield Content`清白，但由于`Yield Content`确实没人在意
那就夺舍了算了，反正现在`Async Content`也被`Array Content`/`Async Contents`夺舍了，正好天下大同，归一`Content`形式，多好
顺带为`Array Content`/`Async Contents`加点内容，修点Bug
将`Yield Content`的编程器改为传入`Async Contents`的编译器
为`Array Content`/`Async Contents`增加第四个参数，用于表示结果
修复【盗书】在主机上因客机中断导致的Bug
测了，能跑
感谢 @1937475624 的协助
无需适配，除非有人改了`Yield Content`的编译器

夺舍`Yield Content`，增加`result`，修复Bug

---

node_modules/@types/noname-typings/NonameAndroidBridge.d.ts
node_modules/@types/noname-typings/cordova-plugin-device.d.ts
node_modules/@types/noname-typings/cordova-plugin-file.d.ts
noname/init/cordova.js
noname/ui/create/menu/pages/otherMenu.js

安卓
需要对旧版安卓客户端进行淘汰
游戏内需要一个便捷查看内核信息和切换webview实现的操作
添加安卓客户端版本限制,菜单增加内核查看和修改功能
测试通过
无

添加安卓客户端版本限制,菜单增加内核查看和修改功能

---

service-worker.js

无
关联 #2260 ，由于Worker的特性，`core-js`并不会为`Service Worker`提供`Iterator#some`，导致旧浏览器无法正常启动`Service Worker`
将`Iterator`转换成`Array`
测了，能跑
无需适配

fix: old browser doesn't support `Iterator#some`.

---

game/game.js
noname/get/compatible.js

无
之前的`Get#coreInfo`的特性不符合现在无名杀的需求
现在`Get#coreInfo`在检测到`navigator.userAgentData`但检测不到Chromium环境的情况下，将继续进行对userAgent的正则判断，而不是直接返回`other`
现在`Get#coreInfo`在解析版本号数字时，若第一位解析的结果为`NaN`，则直接假定所有位为`NaN`；反之，在其他位解析出`NaN`时，返回`0`
现在除了`navigator.userAgentData`和`other`，均通过统一的方式解析版本号
在Chromium, Firefox和Electron上均测试正常
Safari因为条件困难没测试，理论正常，而且Safari用户应该会被拦在别的地方，用不到`Get#coreInfo`
> 什么地狱笑话
无需适配

更改`Get#coreInfo`的一些特性

---

game/game.js

macOS，Electron客户端
修复macOS下__dirname不能正确获取，导致扩展读取导出异常的问题。
该pr与[此pr](https://github.com/nonameShijian/noname/pull/4)的区别在于，后者还修复了“拖拽安装”扩展中的路径问题，并为客户端添加了macOS的打包脚本。
在`game/game.js`中，在macOS平台下，修改`__dirname`的获取逻辑，利用`process.resourcesPath`取得正确路径。
进行扩展创建、保存、导入、导出操作，能正常操作扩展。
一般无需适配，未使用`__dirname`的扩展需检查路径是否正确。

修复macOS系统`__dirname`错误

---

.github/workflows/close-stale-issues.yml

无
联系 #2344 ，添加自动化的关闭issue操作
添加[actions/stale](https://github.com/actions/stale):
- 对于未活跃超过60天的issue和超过90天的PR，若被标记为【Note:Pending】或【Note:Unclear】，将被标记为【Note:Legacy】
- 标记为【Note:Legacy】的issue，7天内仍然未活跃将被关闭；标记为【Note:Legacy】的PR，30天内仍然未活跃将被关闭
- 被标记为【Status:Preparing】的PR和issue将不会被标记为【Note:Legacy】
- 任何有指派人的issue/PR或位于里程碑的issue/PR将不会被标记为【Note:Legacy】
具体可参阅源文件
没测试，但理论上可行
无需适配

feat: add workflow of closure of stale issue and pull-request.

---

character/refresh/skill.js
character/sp/skill.js
noname/library/element/player.js

冇
hasUsableCard进一步优化
bugfix
新增hasUsableCard过一次技能的onChooseToUse/Respond以过部分主动技能检测
新增前置判断角色手中卡牌检测的respond通过部分
新增拒绝技能次数到达上限的技能通过hasUsableCard检测
修复SP刘备惊雷死亡后仍可选择角色补牌的bug
测了，目前没遇到问题，且有争议的技能均能顺利通过技能检测
修改了`lib.element.player.hasUsableCard`的扩展

hasUsableCard进一步优化；bugfix

---

noname/library/element/content.js

之前提过一个issue: [2436](https://github.com/libnoname/noname/issues/2436)，实际上出错的代码在[noname/library/element/content.js](https://github.com/libnoname/noname/blob/master/noname/library/element/content.js)文件中出现了两次，大佬在[PR 2465](https://github.com/libnoname/noname/pull/2465/files#diff-8ce9abd1be8c801dcf85a2230f1af14d5085cb69bd1b60d8d106ecaf0436c6c4)中修了其中一处。我按照这个改法把另外一处也改了。

修复“一个可能的逻辑错误”，下

---

noname/init/index.js
noname/library/index.js

无
在以前网页端无法使用fs的时候，为了兼容网页端，扩展加载是直接读取储存在`lib.db`/LocalStorage里的信息，这导致添加扩展无法直接将扩展放入文件夹，必须通过无名杀内部导入扩展或“万能导入”才能让扩展被加载
现在不一样了，虽然本质上是ban了不能用fs的网页端（其实还没完全ban），但至少从网页端到手机端都能使用上文件管理，故可以考虑添加扩展自动导入
添加“自动导入扩展”选项，开启后将在启动时自动检索扩展文件夹，并导入未导入的扩展
- 由于可能存在某一平台下文件管理的效率低下，导致启动页加载效率过低，故不自动开启，有需求请自行开启
- 当以此法导入新扩展时，为防止一些特殊情况，此扩展将默认被关闭
测了，能跑
无需适配
~~当然你可以把提供类似功能的扩展删了~~

为无名杀添加自动导入扩展的功能

---

noname/library/concurrent/index.d.ts
noname/library/concurrent/index.js
noname/library/index.js

无
实际上也没什么实际痛点，但写`Array#map + Promise.all`写烦了，就从隔壁C#抄了个类过来
提供`lib.concurrent`静态类，其中暴露的方法为:
```typescript
export class Concurrent extends Uninstantable {
/**
* 执行一个异步的for range循环
*
* 由于异步的特性，你无法中途中止循环，但你可以提供一个AbortSignal，来使回调函数能通过该信号中止
*
* > 步长为1主要是C#的Parallel.ForAsync的步长只能为1，~~绝对不是我懒~~
*
* @param start - 开始索引（包含）
* @param end - 结束索引（不包含）
* @param callback - 回调函数，接收当前索引和提供的信号；如果回调函数不包含异步操作，则将退化为同步操作
* @param options - 可选参数，具体可参阅`ConcurrentOptions`
* @returns 返回一个Promise，包含执行过程中所有的异常
* @throws {TypeError} 如果提供的回调函数不是一个函数
* @example
* // 使用AbortController来控制循环的终止
* const controller = new AbortController();
* await Concurrent.for(1, 100, async (i, signal) => {
* 	if (signal.aborted) return;
* 	await someAsyncOperation(i);
* }, { signal: controller.signal });
*/
static async for<T extends …
```

增加一个提供异步迭代方法的类

---

noname/library/index.js
noname/ui/create/index.js

无
为 #2578 和 #2576 修一点细节相关
为旧的缩放设置进行兼容，现在启动无名杀会自动进行旧设置到新设置的转换
对缩放设置的显示进行调整，现在显示的缩放比例均会以两位小数的形式显示
> 该PR并未解决 #2403 的问题，目前无名杀要实现后确认需要动态添加元素，鉴于未来的更新计划，缩放更改后的确认将于菜单重写实现
测了，能用
无

对新缩放设置进行些调整

---

mode/brawl.js

修改乱斗模式，在创建关卡的时候可以选择一个"循环测试"的模式。
在这个模式下，此关卡下的场景会循环地自动对局，直到手动停止。
只修改一个mode/brawl.js文件，在乱斗模式下其他旧的乱斗模式、身份模式经测试是正常的。
"循环测试"

修改乱斗模式，在创建关卡的时候可以选择一个"循环测试"的模式

---

card/huodong.js
card/sp.js
character/huicui/skill.js
character/jsrg/skill.js
character/mobile/skill.js
character/offline/skill.js
character/old/skill.js
character/onlyOL/skill.js
character/refresh/skill.js
character/sp/skill.js
character/xianding/skill.js
character/yijiang/skill.js
game/package.js
mode/guozhan/src/skill/character/yingbian.js
noname/library/element/player.js

所有
群友反馈
1.开黑季卡牌更名为活动卡牌
2.重写部分直接结束回合的技能保证能正常触发回合结束时的时机（包括卡牌躺赢、旧曹叡的明鉴、国战司马昭的昭然、合陆逊的待劳） 
3.修复庞宏一技能弃置牌没有过mod的bug
4.威吕布和威张辽的连招技用来标记的子技能从group改为init的时候添加，避免因为主技能被封印导致连招提示异常
5.修复银月枪结算的bug #2713 
6.为player.disableSkill增加保底
7.你死我活遇到十常侍修正报错
8.曹植酒诗save忘记判断是否濒死角色是自己了
9.神卢植围铸重写
已在本地测试
无

bugfix&卡牌包名修改

---

noname/library/index.js

无
※有些扩展会存在隐藏了“删除此扩展”的选项，或者因为部分安卓手机权限的问题，导致在游戏内无法直接删除扩展，或者删除了扩展，但是extension文件夹的扩展文件还在，于是有些时候会直接在文件夹内删除扩展，这会导致关于扩展的lib.config[extension_${extensionName}_]的配置文件还在，最显著的就是lib.config.extensions内还有该扩展存在，以及Lib.config.extension_extensionName_的配置信息还存在，如果有某个扩展以检测另一个扩展是否存在或者打开而开启某个功能，就会导致报错
※该选项点击后将检查lib.config.extensions内的扩展，根据扩展名检查相对应的扩展文件夹是否存在，如果存在即检查是否存在extension.js/info.json文件，如果都不满足就执行game.removeExtension(extensionName)来删除扩展的配置文件。
※该选项实现比较粗暴/简单，所以点击打开时需充分小心，同时需要注意的是，我在之前遇到过一个扩展，扩展文件夹是“aaa”,扩展的extension.js和info.js写的扩展名是“bbb”，如果你的扩展内有这样的扩展，请勿打开此选项。
PC本地客户端充分测试通过，安卓端未测试
建议扩展储存信息使用game.saveExtensionConfig，但本次提交不影响扩展。

添加重置无效扩展配置信息选项

---

character/clan/skill.js
character/extra/skill.js
character/huicui/skill.js
character/onlyOL/skill.js
character/refresh/skill.js
character/shenhua/skill.js
character/sp/skill.js
character/tw/skill.js
character/xianding/skill.js
character/yijiang/skill.js
mode/guozhan/src/skill/character/yingbian.js
noname/library/element/content.js
noname/library/element/player.js

无
因为白喵反馈了chooseToMove点击不同区域按钮不能交换的问题喵（比如神诸葛亮七星交换牌哦，只能拖动交换而不能点击交换喵）
修复了一下chooseToMove点击不同区域按钮不能交换的问题喵
顺便把所有涉及到chooseToMove仅交换而不移动牌（即区域牌数量保持不变）的情况去掉了全选按钮喵
进行了简单的测试喵，选择点击不同区域的按钮会正确执行交换而不是取消选择喵
七星等仅交换牌隐藏的全选按钮喵
无

修复chooseToMove对于跨块点击无法交换的问题，为所有只能交换的chooseToMove添加noChooseAll

---

character/huicui/skill.js
character/newjiang/skill.js
character/onlyOL/skill.js

修复 #2981 反馈的bug
1.修复谋庞统【鸿图】/张奂【戍国】单机单人控制下未切换控制导致看不见对话框的bug；
2.遗漏的祢衡【舌剑】allowChooseAll适配；
已测试

bugfix；遗漏的allowChooseAll适配
